endlessm/gnome-software

- configure.ac
- src/plugins/gs-plugin-fedora-distro-upgrades.c
- src/plugins/gs-plugin-xdg-app-reviews.c
Cherry-pick from upstream so g-s compiles with json-glib >= 1.1.2.
> Depend on a new enough json-glib to drop the compat defines

- debian/changelog
- debian/rules
Reviews and GNOME Shell Extensions should not be part of the UI in Endless's use of GNOME Software.
> Disable reviews and shell-extensions when building

- debian/rules
I have noticed that the xdg-app plugin is not shipped in the deb so I have enabled in debian/rules to see if that makes a difference (it should be built if xdg-app is available, which is a deb build dependency).
I have also disabled the ODRS plugin as we do not want to worry about ratings ATM.
https://phabricator.endlessm.com/T11467
> Fix built plugins when generating the Debian package

- debian/control
The names of the xdg-app dependencies have changed: from libxdgapp to
libxdg-app.
> Update xdg-app dependencies

- debian/rules
They were not being correctly built and due to that it was failing when
initializing the GsFlatpak object in a second plugin.
https://phabricator.endlessm.com/T12068
> Fix building the flatpak plugins

- src/gs-image-tile.c
- src/gs-image-tile.ui
- src/gtk-style.css
This is accomplished by including the icon in the image tile's normal
view and changing how the main image is assigned to it: instead of
applying it as the background of the entire widget, it is applied as
the background of a widget that is layed over the mentioned icon. This
way, when there is a main image the icon is hidden behind it, but when
there is none, the icon is visible.
This allows the GsImageTile to display a graphical asset related to its
app even with apps that do not have that main image, which keeps a good
UX.
See https://phabricator.endlessm.com/T12144
> Show the app's icon its image tile when there's no main image

- src/gs-shell.c
This avoids destroying a category row that may be eventually selected
which was leading to a crash.
https://phabricator.endlessm.com/T12194
> Select the overview mode before clearing categories

- src/gs-app.c
- src/gs-image-tile.c
- src/plugins/gs-plugin-eos.c
Currently we pass the URL of the thumbnail directly to GtkCSS - this will create a lot of unnecessary load and network traffic every time gnome-software is booted up. It also doesn't work offline.
We want to cache these thumbnails. To do that, we need to download and save them to the cache directory using libsoup and then pass the filesystem location to GtkCSS.
In some cases, we might end up downloading files after the `_refine` functions on plugins have been run. A signal was added to GsApp to indicate that new metadata has been added after the fact so that interested views can refresh themselves appropriately.
https://phabricator.endlessm.com/T12142
> Add client side of thumbnails downloading

- src/plugins/gs-plugin-eos.c
This is useful for QA to test that the cache is working as expected.
https://phabricator.endlessm.com/T12142
> eos: Make a note of when we got a cache hit

- src/gs-shell-details.c
This change is needed for EOS because the kudos section can be
misleading and confusing for our users.
https://phabricator.endlessm.com/T12265
> Hide the kudos section in the app's details page

- src/plugins/gs-plugin-eos.c
These changes correctly adopt the system apps, preventing the EOS plugin
from managing apps that belong to the flatpak plugins instead.
https://phabricator.endlessm.com/T12378
> eos: Prevent stealing apps from flatpak plugins

- src/plugins/gs-plugin-eos.c
This is in order to avoid repeated entries in the installed page (the
original name + renamed one).
https://phabricator.endlessm.com/T11786
> eos: Blacklist renamed apps

- src/gs-shell-updates.c
Instead of the update dialog, since we don't provide update details for
our flatpak bundles and runtimes yet.
https://phabricator.endlessm.com/T12495
> updates: launch app page when clicking on update row

- src/gs-shell-overview.ui
When a category is empty, GNOME Software displays the
"No Application Data Found" message. This message, by
design, has a bigger font size which - combined with
the Large Text accessibility setting - renders GNOME
Software unshrinkable to an acceptable low resolution
size.
To fix that, make the "No Application Data Found" wrap
the words when needed.
https://phabricator.endlessm.com/T11698
> overview: wrap "No Application Data Found" label

- src/gs-shell-details.ui
The Details page uses a fixed size frame, which doesn't
scale down when running on low resolution devices. This
renders the main window way too big on low resolution
displays.
Fix that by making the Details page scroll horizontally
when needed.
https://phabricator.endlessm.com/T11698
> details: enable horizontal scroll when needed

- src/gs-shell-details.c
This is in order to avoid the user seeing the wrong license that we have
in our Flatpak apps but should be properly fixed later.
https://phabricator.endlessm.com/T12854
> Hide the license details in the details page

- src/gs-shell-details.c
Currently the apps do not have the correct developer name and thus it
should not be shown.
https://phabricator.endlessm.com/T12859
> Hide the developer name in the details page

- src/plugins/gs-plugin-eos.c
It was getting the assigned management plugin's name without copying it,
so when it was reassigned, the original name would be freed which led to
a possible memory corruption when assigning it back.
https://phabricator.endlessm.com/T12538
> eos: Fix management plugin use in gs_plugin_update_app

- src/plugins/eos-external-apps-build-install
- src/plugins/gs-flatpak.c
This regenerates the summary and appstream data to keep gnome-software
happy when it updates flatpak remotes.
> external-apps: Update repo after deleting app

- debian/postinst
gnome-software will expect the repo to contain a summary and appstream
branch when updating. Otherwise, it marks the repo as broken. Initialize
the ostree repository if necessary and regenerate the metadata with
`flatpak build-update-repo`.
> postinst: Ensure external apps repo initialized

- src/plugins/gs-plugin-eos.c
A user that installs an app that's available in a certain locale by
having switched to it temporarily should still see it when they switch
back.
https://phabricator.endlessm.com/T12910
> eos: Do not blacklist apps based on locale if they're installed

- debian/gnome-software.install
Or gnome-software will not be able to find it.
> Install external apps script

- debian/gnome-software.postrm
When purging, the external apps setup and g-s-helper user should be
removed.
https://phabricator.endlessm.com/T12949
> Cleanup external apps setup on purge

- data/Makefile.am
Since it's generated by configure, it will be distributed and
distcleaned automatically.
@dbnicholson
> Remove redundant listing of polkit rules file

- src/gs-shell.c
The problem was that when the key selected a new row, when calling
side_filter_select_by_mode apparently no row was selected (unlike
what happens when using the mouse to select the category) and thus
the code would always select the first row that has the category
mode.
These changes prevent the wrong behavior mentioned above from happening
by selecting the row that matches the currently set shell category when
no row has been selected.
https://phabricator.endlessm.com/T13133
> Fix using the arrows to navigate through categories

- src/gs-shell-installed.c
If an app is uninstalled from outside the installed view (i.e. in the
app's details view), then it would not be removed from the list of
installed applications. Moreover, the app row's button would change to
"Install" but clicking it would just try to remove the app again.
These changes hide the app row from the installed view if its state has
changed and it is now available or unknown (because we still want to
show it there when it is installing).
> Remove an app from the installed view when it's uninstalled

- data/eos-external-apps-enable.service.in
ConditionNeedsUpdate only works if the service runs before
systemd-update-done.service. Unfortunately, this also means running with
DefaultDependencies=no in sysinit.target. Since this operation is so
lightweight (it just run flatpak remote-add and flatpak remote-modify),
just have it run on every boot.
https://phabricator.endlessm.com/T12949
> external-apps: Really run enable service

- src/gs-app.c
- src/gs-app.h
- src/gs-application.c
- src/gs-common.c
- src/gs-self-test.c
It was not finding a plugin for the app that had just been installed
when the user clicked the notification to go into the app's details
page.
This patch adds a new method to create a GsApp out of a unique ID,
setting as much info as it can from the ID, and thus increasing the
chances of the app getting adopted by some plugin.
https://phabricator.endlessm.com/T13244
> Fix launching app's details from the "installed" notification

- src/plugins/gs-flatpak.c
The logic for setting an app as updatable works by comparing the current
commit of an app with the latest one available.
However, if an app no longer exists in its remote, then the latest
commit is being set as NULL, thus resulting in a wrong update for the
app in GNOME Software.
This patch simply checks if the latest commit of an app is not NULL
before comparing the commits in question.
https://phabricator.endlessm.com/T13371
> Do not show an update for apps whose latest flatpak commit is NULL

- src/plugins/gs-plugin-eos.c
Installed knowledge apps of different locales are not being blacklisted
but the blacklisting function is mistakenly returning TRUE which
prevents any further refining of those apps, thus resulting in not
having a custom tile set. This patch fixes that return value.
https://phabricator.endlessm.com/T13306
> eos: Fix displaying the custom app tile in KApps of different locales

- src/plugins/gs-plugin-eos.c
When different GsApp objects exist for the same application, then
they will become blacklisted because in the
gs_plugin_eos_blacklist_kapp_if_needed method one object will replace
and blacklist the other. Since they refer to the same app, then that
app would end up blacklisted.
This patch verifies not only the object that has been cached but also
compares the IDs to see if they refer to the same app, in order to
avoid the issue mentioned above.
https://phabricator.endlessm.com/T13396
> eos: Prevent blacklisting apps that represent the same app

- src/plugins/gs-flatpak.c
- src/plugins/gs-flatpak.h
- src/plugins/gs-plugin-flatpak-system.c
- src/plugins/gs-plugin-flatpak-user.c
Even if there is a download-updates setting, the Flatpak plugins are not
honoring it, meaning that Flatpak updates are always downloaded on
refresh time (and deployed later).
With these changes, the original behavior is still used if the mentioned
setting is true. Otherwise, it shows updates for refs that even if they
do not have downloaded updates and fetch those when the user
deliberately updates the apps.
https://phabricator.endlessm.com/T13407
> Perform Flatpak updates according the download-updates setting

- src/gs-app-row.c
- src/gs-shell-updates.c
The "update" label is used instead of "install" to better support
users' expectations.
https://phabricator.endlessm.com/T13593
> trivial: Use the "update" label in the updates page's buttons

- src/gs-shell-updates.c
We need things to always happen immediately when pressing the refresh
button and not only if the cache is older than 10 minutes.
https://phabricator.endlessm.com/T12998
> Do not set a cache age on manual refresh

- src/plugins/gs-plugin-eos.c
Regardless of the user's current language, we've been asked
to not show the encyclopedia apps in the app center for users
of the zh_CN image personality.
Note that we check for the "com.endlessm.encyclopedia" prefix
rather than a specific ID in order to block any localized
version of the encyclopedia.
https://phabricator.endlessm.com/T13291
> Block encyclopedia apps in China

- src/plugins/gs-plugin-external-apps.c
We need apps to have all the appstream data on them before we
eventually manage them as external apps.
This also solves an issue where broken external apps (an installed
external app without its external runtime installed) were showing
up in the installed list.
https://phabricator.endlessm.com/T13804
> external-apps: Run after the "appstream" plugin

- src/plugins/gs-plugin-external-apps.c
This patch changes the order of the removal for external apps: now the
headless app is removed before the external runtime because if it fails
or is cancelled for some reason, the app may still be used.
It also uses the helper script to remove the external runtime so that
the removal process doesn't ask for the user's password twice.
https://phabricator.endlessm.com/T13807
> external-apps: Improve the removal of apps

- src/gs-app-row.c
The label looks broken and brings little value that way.
https://phabricator.endlessm.com/T13819
> Remove the "installed" label from search results

- src/plugins/Makefile.am
- src/plugins/gs-plugin-flatpak-appstream.c
This plugin is needed temporarily to fix the issue that the Flatpak
plugins (which also handle their remote's appstream files) need to run
after the appstream plugin but the this one needs to have also the
flatpak appstream symlinks in place. This was causing an empty overview
when GNOME Software was launched without the symlinks.
https://phabricator.endlessm.com/T13855
> Add gs-plugin-flatpak-appstream

- src/plugins/gs-plugin-eos.c
It was happening in the gs_plugin_update_locale_cache_app function.
https://phabricator.endlessm.com/T13915
> eos: Avoid calling a method on a GsApp NULL pointer

- src/plugins/gs-plugin-external-apps.c
This is defensive code that should be able to fix an issue where an
installed external runtime has its state as "unknown".
https://phabricator.endlessm.com/T14075
> external-apps: Double-check/reset a cached external runtime's state

- src/plugins/eos-external-apps-build-install
This should save twice the size of the external apps' Debian packages
and one time the size of tarball external apps' tarballs.
https://phabricator.endlessm.com/T14145
> external-apps: Remove apps' assets when they're no longer needed

- configure.ac
- src/plugins/gs-flatpak.c
- src/plugins/gs-flatpak.h
- src/plugins/gs-plugin-eos.c
Drop the need on our custom system based on the `/etc/gnome-software/flatpak-extra.conf` file and use flatpak's new APIs instead to check the default-branch attribute for a remote, pulling it from the server's summary file when needed.
https://phabricator.endlessm.com/T13403
> Handle default branches using flatpak's API only

- debian/control
This is required for flatpak_installation_update_remote_sync ()
https://phabricator.endlessm.com/T13403-debian
> Set minimum required version of flatpak to 0.6.13

- src/plugins/gs-plugin-eos.c
This is done only for the Endless remotes and is a solution for when
existing users upgrade the OS and boot into an offline state (meaning
they won't be able to fetch the default branches).
https://phabricator.endlessm.com/T14206
> eos: Use fallback branches when no default ones are fetched

- src/plugins/gs-plugin-eos.c
When apps are launched through a helper desktop file, e.g. Chrome,
that is the file that needs to be added to the desktop and not the
app's original one.
https://phabricator.endlessm.com/T14209
> eos: Support desktop icons for apps that use helper desktop files

- src/gs-application.c
Otherwise, depending on the action with which GNOME Software is
activated, it may not monitor the network which means it will assume
that it is always offline.
https://phabricator.endlessm.com/T14226
> Start monitoring the network when the UI is initialized

- src/gs-app.c
- src/gs-app.h
- src/plugins/gs-plugin-eos.c
- src/plugins/gs-plugin-external-apps.c
Even though we use Flatpak for managing our applications and that
is independent from the OS version, there are some applications that
may use in a hybrid way: we use Flatpak for the distribution but we
launch them from outside which means that perhaps the OS in question
doesn't have the app helper that launched it. For that reason we want
to be able to blacklist apps if they are not compatible with the OS.
https://phabricator.endlessm.com/T14235
> eos: Blacklist app if incompatible with the OS version

- src/plugins/gs-flatpak.c
- src/plugins/gs-plugin-external-apps.c
This patch fixes a crash that was happening when an external app was
being uninstalled and the user entered its details view.
The problem was that upon entering the details view while the app was
being uninstalled, the app would be refined and there was a race
between what the GsApp's state was and what the Flatpak state was,
so when calling a method that assumed the app to be installed, a seg
fault would occur.
https://phabricator.endlessm.com/T14237
> external-apps: Fix crash while app is being uninstalled

- src/plugins/gs-plugin-eos.c
This prevents prematurely blacklisting apps before knowing if they're
are installed or not.
https://phabricator.endlessm.com/T14266
> eos: Do not blacklist apps before they are assigned a state

- src/gs-shell.c
Upstream has chosen not to show this button in the mentioned views for
different reasons but we need this in order for the UI to be coherent.
https://phabricator.endlessm.com/T13211
> Show the search button in the category and installed views

- src/plugins/Makefile.am
- src/plugins/gs-legacy-external-apps.h
- src/plugins/gs-plugin-external-runtimes-cleaner.c
- src/plugins/gs-plugin-legacy-external-apps.c
The plugin "legacy-external-apps" gets the info about the external
runtime from the installed AppStream data and runs before the "flatpak"
plugin so we can get this info before the app is changed
(removed/updated). That info is set as a metadata item in the GsApp
object.
The plugin "external-runtimes-cleaner" uses the info mentioned above
to remove the external runtimes once an app is updated or removed. It
runs after the Flatpak plugin and ensures that such runtimes are only
removed if the app has been successfully updated/removed.
https://phabricator.endlessm.com/T14442
> Add plugins for cleaning up the legacy external runtimes

- src/plugins/gs-plugin-eos.c
The gs_plugin_add_updates was calling another exported vfunc which
makes the linker confuse about which one to call.
https://phabricator.endlessm.com/T14661
> eos: Fix crash when calling gs_plugin_add_updates

- src/gs-shell-overview.c
- src/gs-shell-overview.ui
The reason is that we still do not have a defined plan for how to use
this section, so it's better to disable it until then.
https://phabricator.endlessm.com/T14706
> Disable the featured banner

- src/plugins/gs-flatpak.c
When an app is updated it may require a new runtime (or new branch),
thus we need to also check for that and install any new runtimes
accordingly.
> Install needed Flatpak runtimes when updating an app

- src/plugins/gs-flatpak.c
The apps rely on the runtimes declaration in the repo's AppStream file.
This information however relates to the app's version that is given by
the server, which may need a different runtime (because of a update)
than what is installed; thus, these changes drop the check that verifies
whether the runtime is installed before launching the app, delegating
that responsibility to Flatpak itself which prevents mistakenly assuming
that the runtime is not installed.
https://phabricator.endlessm.com/T14905
> Fix launching Flatpak apps

- src/org.gnome.Software.desktop.in
https://phabricator.endlessm.com/T14837
> Fix missing name for GNOME Software

- src/plugins/gs-flatpak.c
The idea is to use GNOME Weather from the GNOME flatpak repository
but we can't do it now because we need it to be patched so that it
allows overriding its application ID (needed for Endless Coding).
See the upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=776315
In the meantime we are creating our own flatpak for GNOME Weather,
so we need to blacklist the one from GNOME to avoid duplicates.
https://phabricator.endlessm.com/T14720
> Temporarily added GNOME Weather to the list of blacklisted apps

- src/plugins/gs-appstream.c
When gs-appstream creates a new runtime but returns a cached one instead
it must ensure that the cached runtime has a source set on it. Otherwise
it will later fail when GNOME Software uses any details about the
runtime.
https://phabricator.endlessm.com/T15042
> Ensure that the cached runtimes' source is always set

- src/plugins/gs-flatpak.c
When an app has an update and the new updated app needs a different
runtime, unless the AppStream of the repo has been very recently
updated, the app not realize that it needs to eventually install a
new runtime.
These changes get the runtime information from the remote ref (meaning
the real runtime for the app) before deciding whether the runtime
needs to be installed which prevents the problem above.
https://phabricator.endlessm.com/T15062
> Fix launching apps after updating

- src/plugins/gs-plugin-eos.c
The logic was not checking all the updatable states (there's
"updatable" and "updatable live"). This patch uses the convenience
function gs_app_is_installed instead of checking the statuses
directly.
https://phabricator.endlessm.com/T15010
> Fix updating the app desktop shortcuts when apps are updatable

- src/gs-app.c
- src/gs-self-test.c
If the progress being set is greater than 100 a warning should be
returned and the value be limited to 100.
https://phabricator.endlessm.com/T15131
> Warn and limit the progress set on a GsApp

- src/plugins/gs-plugin-eos.c
This is done automatically by the Shell for all applications except
Chrome as it uses a special desktop file instead of the one provided
by Flatpak. Nonetheless, instead of using a different logic only for
Chrome, this patch always attempts to remove the shortcut for any
Flatpak app that is removed (as it's future proof in case more apps
have special desktop files in the future).
https://phabricator.endlessm.com/T15130
> eos: Remove shortcuts directly when applications are removed

- src/plugins/gs-plugin-eos.c
The EOS plugin adds a shortcut in the desktop to the apps after they
are installed and this was being done without checking if that shortcut
was already present.
This has not been a problem because applications (usually) do not get
their shortcut in the desktop when they are not installed but this
changed for Google Chrome where we ship some images already with a
special shortcut to it. The problem is that when a shortcut is added
to the desktop while it is already present in there it gets moved to
the end of the list of shortcuts which is not the desired behavior
in this use-case.
These changes fix the mentioned problem by simply avoiding to add a
shortcut to the desktop if it is already there.
https://phabricator.endlessm.com/T15185
> eos: Do not add a shortcut to the desktop if it's already there

- src/gs-app.c
Make sure progress gets reset when recovering state, to prevent
confusing initial states when going through more than one attempt.
https://phabricator.endlessm.com/T15569
> Reset GsApp's progress to zero when recovering a non-transient state

- src/gs-plugin-loader.c
This will make sure that, even after a successful installation, the
progress bar is reset to zero, to prevent confusion in the unlikely
event of the user going for a install + uninstall + reinstall process.
Note: This patch is a backport from the one upstream without the unit
tests, that would cause lots of conflicts due to a different baseline.
See https://git.gnome.org/browse/gnome-software/commit/?id=89b5dcde
https://phabricator.endlessm.com/T15569
> Initialize progress to zero right before and after processing and action

- src/plugins/gs-install-appstream.c
After the change in gnome-software-data@c7028eee, the eos-extra.xml file
will no longer contain full <components> but partial ones, as they are
meant to be merged with the full versions of them (provided by the distro
wide AppStream collection XML), and therefore declare the merge='append'
attribute as described in the Appstream specification [1].
Because of this, it is no longer possible to validate this file by using
use as_store_from_file() to load the XML and then checking that it has
at least some elements, because that will never be the case as now that
file does not contain any complete component by itself, just extended
information for the already present ones.
Thus, we have to drop this validation step and believe that the file
is valid as long as it's a valid gzipped-XML, …
> Don't try to validate the eos-extra.xml file by parsing it with AsStore

- src/plugins/gs-plugin-eos.c
When adding a shortcut, instead of checking if it is already in the grid
(which means it can be hidden inside a folder), we verify whether it is
in the top level of it and add it if it is not. This ensures the icons
are always added in a visible way from GNOME Software, even if they're
configured to be inside a certain folder.
https://phabricator.endlessm.com/T15941
> eos: Make sure all added shortcuts are in the top level

- src/gnome-software.ui
- src/gs-application.c
- src/gs-shell-category.ui
- src/gs-shell-overview.ui
- src/gs-side-filter-row.ui
- src/gtk-style.css
This PR changes GNOME Software to use the light theme variant. This is how it looks:
Per the mockups at https://endlessm.invisionapp.com/d/main#/projects/prototypes/10298019
https://phabricator.endlessm.com/T16197
> Switch to the light theme

- src/gs-image-tile.c
- src/gtk-style.css
The loading tiles are too dark and create too much
contrast with the new light theme.
Fix that by using subtler colors, per proposed mockups.
https://phabricator.endlessm.com/T16197
> Make loading tiles less proeminent

- src/plugins/gs-plugin-eos.c
Roundtrip through gs_utils_get_desktop_app_info(), which will allow us
to use the correct app ID even in the case of apps using the kde4
prefix.
https://phabricator.endlessm.com/T16469
> eos: consider kde4 prefix when adding the app to the desktop

- src/gs-shell.c
We can't just check for the override being non-NULL; we also need to
check that it's not an empty string and fall back to the default in that
case.
https://phabricator.endlessm.com/T16302
> shell: don't set an empty featured category name

- src/plugins/gs-plugin-legacy-external-apps.c
This is a covenience plugin that is used as an aid to clean up the
legacy runtimes, and as such, it should not make the regular GNOME
Software operations fail (i.e. it should never return FALSE from its
interface implementation methods).
https://phabricator.endlessm.com/T16664
> Do not fail in the legacy-external-apps plugin

- src/plugins/gs-flatpak.c
Due to some bug or concurrent use of Flatpak, sometimes an update that
the user is installing happens to be already installed. In that case,
upon failing to update the app via GNOME Software, it should check the
error and just mark the app as installed if the update is already
installed: thus behaving has if the update had succeeded which is what
has the minimum impact in the UX.
https://phabricator.endlessm.com/T16370
> Do not fail when updating an app if the update is already installed

- src/gs-image-tile.ui
- src/gtk-style.css
In languages such as Birmanese and Hindi the characters would go below
the bottom of the tiles, so this patch pushes the text a bit to the top,
avoiding that problem.
https://phabricator.endlessm.com/T16860
> Fix text vertical alignment in the image tiles

- src/plugins/gs-flatpak.c
In order to ensure we have the default branches for the eos-apps repo we
are updating the metadata of every repo that doesn't have that info set
yet.
Since updating the metadata takes a couple of seconds and there are
repos that do not have a default branch set, this operation is taking
several seconds, delaying the launch of GNOME Software.
These changes restrict the check for the default branch only for the
eos-apps repo (as this was the motivation for the logic initially in any
case).
https://phabricator.endlessm.com/T16924
> Do not try to fetch the default branch for every repo

- plugins/eos/gs-plugin-eos.c
https://phabricator.endlessm.com/T14669
> Do not blacklist GNOME Weather coming from the GNOME apps repo

- plugins/eos/gs-plugin-eos.c
The flatpak previously had problems rendering YouTube, but that
has been fixed upstream.
https://phabricator.endlessm.com/T17264
> Un-blacklist Epiphany

- src/Makefile.am
- src/discovery-feed-content-provider-dbus-interfaces.xml
- src/gs-application.c
- src/gs-discovery-feed-content-provider.c
- src/gs-discovery-feed-content-provider.h
- src/meson.build
- src/org.gnome.Software-discovery-feed-content-provider.ini
Similar to the included Shell Search Provider, this provider
will include the top five apps to install to populate the
discovery feed with content.
https://phabricator.endlessm.com/T16977
> app: Add an EOS Discovery Feed Content Provider

- lib/gs-plugin-loader-sync.c
- lib/gs-plugin-loader-sync.h
- src/gs-search-page.c
- src/gs-shell-search-provider.c
I did some testing and investigation I isolated two issues:
1) The ID used is not unique, causing the search to fail.
2) In `handle_get_result_metas`  the function `gs_plugin_loader_get_app_by_id` returns empty app structure therefore when the user type a search in the desktop search bar no app results are shown.
~Fixes:~
~1) Commit "search-provider: use the app unique id".~
~2) Commit "search-provider: cache app data in search_done_cb".~
~I could not find a way to fix that function, so I implanted a work around. Using a greedy approach, I save the app data in a cache in the `search_done_cb`, instead of in the `handle_get_result_metas`. The result is more data stored in the cache.~
~Also to make it work, I had to pass an empty string instead of the search terms. (see "search-provider: …
> Fix gs shell search provider

- src/gs-discovery-feed-content-provider.c
In order to display the details page we
need to use the unique-id for g-s to find
the app. The same is done for the search
provider.
https://phabricator.endlessm.com/T17874
> DiscoveryFeed: use the unique app id

- plugins/eos/Makefile.am
The EOS plugin was not being linked with libflatpak and this somehow
didn't show up as a problem except on 3.2 images.
https://phabricator.endlessm.com/T18119
> eos: Link with libflatpak

- plugins/eos/gs-plugin-eos.c
Since 3.2, EknServices links to com.endlessm.apps.Platform rather than com.endlessm.Platform, so it's better to group these two together for update purposes, and allow com.endlessm.Platform to appear "normally" by itself.
https://phabricator.endlessm.com/T18238
> group EknServices together with apps runtime, rather than the old EOS runtime

- plugins/eos/gs-plugin-eos.c
After discussing with Joaquim we think it's better to group all of
the runtimes for Endless together, as long as we have/need a separate
Endless OS runtime - hopefully over the next 3-6 months we'll be
able to move off it onto the freedesktop/gnome/SDK stack and remove
it.
https://phabricator.endlessm.com/T18238
> eos: re-add Endless OS Platform to proxy app

- plugins/eos/gs-plugin-eos.c
The upstream Flatpak now includes the Telepathy daemons, so this
works on Endless now.
https://phabricator.endlessm.com/T18348
> eos: remove Polari from blacklist

- src/gs-category-page.c
- src/gs-overview-page.c
Some GNOME apps are blacklisted and they are done so by verifying their
name and hostname. However, in some views like the category and
overview, the hostname is not being requested when refining those apps.
This results in a failure to blacklist the mentioned apps.
To fix this, this patch adds the REQUIRE_ORIGIN_HOSTNAME flag to the
refine flags in the overview and category views.
https://phabricator.endlessm.com/T18685
> Fix blacklisting of GNOME apps

- plugins/eos/gs-plugin-eos.c
The flatpak version of dconf-editor does not show the default values
specified in eos-theme, and is missing a lot of keys (e.g., under
/org/gnome/shell, the only keys are command-history and
icon-grid-layout, and they both complain that "No Schema Found").
https://phabricator.endlessm.com/T18993
> eos: Blacklist dconf-editor

- plugins/eos/gs-plugin-eos.c
The previous attempt was missing the ".desktop" extension.
https://phabricator.endlessm.com/T18993
> eos: Fix blacklist of dconf-editor

- lib/gs-app.c
- lib/gs-plugin-loader.c
These changes avoid a race when apps are refined from within a
different thread, as their properties' notification were being
emitted (and thus triggering) code from those.
Specifically there was a race when setting up the CSS for the
background tile as this code was not getting run from the main
loop.
https://phabricator.endlessm.com/T19321
> Notify apps' property changes from the main loop

- plugins/flatpak/gs-flatpak.c
Instead of listing the installed refs and trying to match the app there,
it instead looks for the app's installed ref directly (which lets
Flatpak manage how to look for it and is much faster).
From some measurements this makes refining apps about 2x faster.
https://phabricator.endlessm.com/T19396
> flatpak: Improve performance of refining an app's state

- plugins/eos/gs-plugin-eos.c
After a2ff48d35186cc612e19ceeb8164b1cb1b645375, core apps (installed in
the system by default) stopped being assigned a state and thus were
geting filtered out. So we need to ensure that such apps are getting
the correct state.
For that reason, now the EOS plugin, besides setting the compulsory
quirk to such apps, also forcibly sets their state to installed.
https://phabricator.endlessm.com/T19482
> eos: Set the installed state for compulsory applications

- plugins/eos/gs-plugin-eos.c
The function that refines the knowledge apps uses a GsFlatpakApp
function to get the app's ref name, but it's not checking if the app
being refined is the expected type. When it is not, this leads to wrong
memory access which can end up in a seg fault.
https://phabricator.endlessm.com/T19490
> eos: Prevent crash when refining knowledge apps

- plugins/eos/gs-plugin-eos.c
By mistake, the condition that checked whether a compulsory app was
installed was inverted. So it would never set the installed state to
those apps.
This patch simply negates the condition, which fixes the issue and makes
core apps be shown again.
https://phabricator.endlessm.com/T19482
> eos: Fix setting the installed state to compulsory apps

- src/gs-updates-page.c
We display the number of updates in the Updates tab but it was never
changed after apps got updated. This patch moves the logic of setting
up the number of updates from the get-updates callback into the
update-ui function, ensuring it gets updated when apps' states change.
For that we had to also calculate the number of updates as the number
of apps that are updatable + the ones with the installing state.
Otherwise we'd be decreasing right after an app starts the update and
not when it succeeds being updated.
https://phabricator.endlessm.com/T19038
> updates: Ensure the update count is updated after each update

- plugins/flatpak/gs-flatpak.c
- src/gs-updates-page.c
The Flatpak plugin was emitting the "updates-changed" signal after
updating every app. This ended up refreshing the updates page after
each Flatpak update which takes a while and reloads the list of apps.
To prevent that, this patch just removes the call that emits the
mentioned signal. There is no downside from this removal because the
updates page already responds correctly to the apps' state changes.
https://phabricator.endlessm.com/T14214
> flatpak: Stop refreshing the updates page after every update

- src/gs-updates-page.c
Since refreshing GNOME Software influences the updates page, that option
should not be given to the user, and thus we should make the refresh
button insensitive when any app is being updated.
https://phabricator.endlessm.com/T19612
> updates: Set the refresh button insensitive when apps are updating

- src/org.gnome.Software.desktop.in
The reason is that when maximizing the window it shows a weird jerky
effect that hinders the smooth UX we always pursue.
https://phabricator.endlessm.com/T19697
> Use the speedwagon when opening GNOME Software

- plugins/eos/gs-plugin-eos.c
We already blacklisted com.microsoft.Skype, which is the app ID
we use for the external app we provide.  Flathub recently made
an app available as com.skype.Client, which shows as a duplicate
in our app center.  Unfortunately, the version on Flathub is not
currently installable on Endless, and besides we would like to
have a migration path for existing users before switching to
the Flathub build, so for now we only want to show our build.
https://phabricator.endlessm.com/T19782
> eos: Blacklist com.skype.Client from Flathub

- po/ar.po
- po/bn.po
- po/cs.po
- po/de.po
- po/es.po
- po/fr.po
- po/gnome-software.pot
- po/hi.po
- po/id.po
- po/meson.build
- po/mr.po
- po/pt.po
- po/pt_BR.po
- po/ro.po
- po/th.po
- po/tr.po
- po/vi.po
- po/zh_CN.po
- po/zh_TW.po
- src/org.gnome.Software.desktop.in
This will allow us to use it from the shell in the desktop grid, as well as to make this particular string searchable from the desktop, so that "More Apps" (or its translation) matches the App Center.
This PR also includes an update to the .pot file and to the relevant .po files, for which I got the translated strings straight from GNOME Shell, where they used to live until now.
https://phabricator.endlessm.com/T18933
> Include "More Apps" as a GenericName in the desktop file

- src/gs-details-page.c
Only the Install and Add-to-desktop button should have the suggested
action, not the Update button. By mistake this change has not been
included in the patch that modifies this for other occasions. So this
patch should be squashed with f52e8f7a4aada021145c54f4fa2b5b3c6a048a2f
in the next rebase.
https://phabricator.endlessm.com/T19764
> Remove the suggested-action style from the Update button

- plugins/eos/gs-plugin-eos.c
This app is only intended for use with the coding feature
and is not yet ready for general use.
https://phabricator.endlessm.com/T19819
> eos: Block coding chatbox if the coding feature is disabled

- src/gs-updates-page.c
Move the logic to decide if we need to reboot or not to run _before_
scheduling an update. Previously we would do it _after_ having applied
the updates, which didn't work because the app flags we were looking at
to make the decision (AS_APP_STATE_UPDATABLE_LIVE) had already changed
at that point (to AS_APP_STATE_INSTALLED).
This fixes a long standing bug where flatpak updates done through
"Update All" would inadvertently bring up the shell reboot dialog and
then lead to a gnome-software crash after dismissing the dialog.
https://bugzilla.gnome.org/show_bug.cgi?id=782618
https://phabricator.endlessm.com/T19785
> updates page: Fix flatpak updates inadvertently triggering a reboot

- src/gs-category-page.c
Otherwise it will keep the scroll value previously set, i.e. if we the
category view to the scroll to the bottom and then change to a different
category, it would still show the view scrolled to the bottom.
https://phabricator.endlessm.com/T19947
> Scroll the category view to the top when reloading it

- plugins/eos/gs-plugin-eos.c
Just like we do for Open Arena, due to the cultural sensitivity
around violent content.
https://phabricator.endlessm.com/T19954
> eos: Blacklist freedoom games for es_GT personality

- plugins/eos/gs-plugin-eos.c
In ab8ffb62f39198785fe730fd13f7f70b7cfc6f0e we started assigning the
plugin that calls for the creation of an app as its management plugin.
This broke launching system apps on EOS because our EOS plugin was
launching only apps that had it as their management plugin (which it
was setting to compulsory apps that had yet none assigned), and those
apps are now getting 'appstream' as their management plugin instead.
To fix this, instead of changing the management plugin, I have replaced
the check for the management plugin with a check for whether the app
being launched is a compulsory, non-flatpak app (just checking for
compulsory should be fine, but this way it is more future proof).
https://phabricator.endlessm.com/T19983
> eos: Fix launching system apps

- debian/rules
This plugin is not only not needed by us but is also creating a problem
by converting any packages that are of the kind "generic" into
OS updates, and this is happening with some of our apps.
https://phabricator.endlessm.com/T20135
> Remove the "generic-updates" plugin

- src/gs-application.c
Enabling and disabling the software sources was broken since we started
calling certain actions after the loading state is finished (by using a
wrapper action that is added to the application's map, which calls the
real action from a secondary map). The problem was that the right action
was being disabled/enabled (so the software sources dialog was not
shown), but the wrapper action's wasn't being affected (and this is the
one that is associated with the menu item).
This patch fixes that by enabling or disabling the wrapper action
instead, since this is the one that belongs to the application's map,
and by binding the "notify::enabled" property of the real app with it.
This way, if in the future we have to disable other actions, this
problem will no longer happen. …
> Fix enabling/disabling software sources

- src/gs-application.c
The patch that fixes enabling/disabling the sources action used
the action name incorrectly when binding the wrapper and real actions'
"enabled" property (it included the "notify::" prefix).
This patch removes that wrong prefix and also a left over declaration
that was producing a warning.
https://phabricator.endlessm.com/T20236
> Fix binding the enabled property of the wrapper and real actions

- plugins/eos/gs-plugin-eos.c
We currently provide LibreOffice as a core app, and now that it is
available on Flathub we want to avoid duplication/confusion.
https://phabricator.endlessm.com/T20253
> eos: blacklist LibreOffice from Flathub

- plugins/eos/gs-plugin-eos.c
We are deprecating our build (based on freedesktop 1.4) and exposing
the version from flathub (based on freedesktop 1.6) instead.
Even though we don't have a clean transition for existing app users,
attempts to build our version against freedesktop 1.6 failed.
https://phabricator.endlessm.com/T20301
> eos: Don't blacklist io.atom.Atom

- src/gs-discovery-feed-content-provider.c
- src/gs-shell-search-provider.c
When searching for apps in the shell, some apps were incorrectly not
being blacklisted (i.e. shown in the search results). This happened to
apps that needed to be blacklisted because they exist both in Endless'
repos and Flathub, and the cause was that the blacklisting logic uses
needs the origin's hostname to be set in those apps, and such flag was
not passed by the search call.
To fix this issue, this patch simply adds the ORIGIN_HOSTNAME refine
flag to the search call in the shell search provider and the discovery
feed content provider.
https://phabricator.endlessm.com/T20268
> Fix blacklisting apps when searching for them

- plugins/core/gs-appstream.c
Trivial backport of the upstream commit [ccc2ca31d7c18bdce140b7b0be48ff3ad577aded](https://git.gnome.org/browse/gnome-software/commit/?id=ccc2ca31d7c18bdce140b7b0be48ff3ad577aded).
> trivial: Fix a critical warning if XDG_CURRENT_DESKTOP is unset

- src/gs-updates-page.c
When manually refreshing GNOME Software (using the refresh button in the
updates page), updates were being downloaded or performed during the
refresh, while the updates page was shown as empty.
This UX is confusing since suddenly users see that updates disappear and
the refresh may take a long time to finish.
Besides, if users can already update all apps by clicking the "Update
All" button, then there's no real advantage in updating apps during a
manual refresh.
This patch stops the the manual refresh from performing app updates, so
it will simply refresh the metadata.
https://phabricator.endlessm.com/T20874
> Do not update apps when manually refreshing

- plugins/eos/gs-plugin-eos.c
When processing apps, we should only add the "compulsory" quirk if their
scope is system, otherwise we risk setting it to apps that still have
some wildcards in their unique IDs (pending being fully refined by a
plugin) which can end up blacklisting the app: apps that are not of the
desktop kind (it can be unknown/wildcard) but are set the compulsory
quirk in order to avoid showing fonts, addons, etc.
In future rebases, this patch should be squashed with
910c9572c9bbb4cd0a26fc475d574810c4f58b10.
https://phabricator.endlessm.com/T20108
> eos: Don't make apps "compulsory" if their scope is unknown

- plugins/flatpak/gs-flatpak.c
The previous code would start looking for com.endlessm.EknServices3 when
installing an SDK3 app. That is incorrect, it should keep using
com.endlessm.EknServices2 until we bump the version number of that
service due to some backwards-incompatibility.
https://phabricator.endlessm.com/T20846
> flatpak: Fix EknServices-picking logic

- lib/gs-plugin-loader.c
The Plugin Loader schedules the GTasks corresponding to some operations
like install/update/upgrade-download, but was running the GTasks using
g_task_run_in_thread_sync from a Thread Pool worker. This is a problem
because this version just runs the GTask's thread function but doesn't
run the callback afterwards. So it broke the use of GPluginLoader's
async calls for the mentioned ops.
For fixing this, turns out we simply have to call the GTask's thread
function directly, as it will end up running the callback.
It also has the advantage that we no longer spawn a thread (GTask's)
from within another thread (GThreadPool's).
https://phabricator.endlessm.com/T16318
> Fix how queued GTasks are processed in the Plugin Loader

- lib/gs-plugin-loader.c
They were mistakenly being added when the plugin loader's action was the
"UPDATE" one, not the "GET_UPDATES" one...
As a result, the updates that were not downloaded were never being
shown, which, in most cases (because as of recently the Flaptka plugin
no longer pre-downloads updates) meant there were no updates whatsoever.
This patch corrects the mentioned mistake and should be squashed
together with 0ba1d4ab2d4b61d4e98dfe0e131bf77ace073688 in a future
rebase.
https://phabricator.endlessm.com/T20874
> Fix adding the pending updates

- plugins/flatpak/gs-flatpak.c
This applies changes to the flatpak remote which come from the summary file,
such as updated keys, titles or the URL. Adding it into the appstream refresh
function means it's behind the timestamp checks and skipping broken remotes,
which avoids adding network roundtrips to the refresh.  libflatpak caches the
summary file in the common case that the remote details have not changed.
https://phabricator.endlessm.com/T20328
> flatpak: add update_remote_sync call to appstream refresh

- src/gs-details-page.c
Recently we added a change where the progress bar is shown empty if the
app has a pending task. The problem is that the visibility of the
shortcut button has not been updated to account for this special
condition, so the result is that apps that are pending an update will
show the shortcut button + the progress bar, making the UI too large and
clunky.
This patch fixes that by simply checking for the pending task in the
logic that toggles the visibility of the shortcut button.
https://phabricator.endlessm.com/T21095
> Make sure the shortcut buttons is hidden when an app has a pending task

- plugins/eos/gs-plugin-eos.c
We blacklist some apps from upstream remotes if they are known not to
work well in EOS, and for ARM we use a whitelist instead. However, if an
app is already installed (by e.g. using Flatpak CLI), then it should
never get blacklisted.
https://phabricator.endlessm.com/T21185
> eos: Do not blacklist apps from upstream if they are installed

- src/gs-background-tile.c
GsBackgroundTile was crashing because it connects to an app's metadata
changed signal but it didn't disconnect from it when the app is changed
or the tile is destroyed.
The crash could be reproduced by repeatedly changing categories very
quickly.
This patch fixes the issue by disconnecting from that signal in the
mentioned conditions.
https://phabricator.endlessm.com/T21190
> background-tile: Fix crash related to an app metadata signal callback

- plugins/core/gs-appstream.c
This avoids a current problem where the objects in the featured page
will be different than the objects representing the same apps in other
views. As a result, the states of what appears to be the same app will
differ: e.g. if a popular app is installed, the same app in the category
view may still show up as not installed.
https://phabricator.endlessm.com/T21218
> Use the global cache when creating popular apps by appstream

- plugins/core/gs-appstream.c
- src/gs-discovery-feed-content-provider.c
Adjust the search handler in `gs-appstream` to allow searching by metadata keys and do the entire search by `Endless::HasDiscoveryFeedContent`. This allows us to remove a previous hack which assumed that all discovery-feed capable apps started with the ID `com.endlessm` and then had to filter for the right ones later.
It might be the case that we are doing the search of the metadata in the wrong place. I took a look at appstream-glib and there doesn't seem to be a particularly obivous process for adding new search fields without hardcoding new ones.
https://phabricator.endlessm.com/T19479
> T19479: Search by Endless::HasDiscoveryFeedContent tag

- plugins/flatpak/gs-flatpak.c
If an app existed in a USB remote but had been cached (loaded) in GNOME
Software before, then it would never get the USB category set to it.
This resulted in apps not being installable from USB because, by not
having the USB category, and being offline, they would get to the
pending state instead.
The reason for the USB category not being set on previously cached apps
was that we were setting it only to the AsApp objects of the Flatpak
plugin's internal store as the GsApps that are created from these
objects will also get the same categories. However, if the apps had
already been created before, no categories would be set.
This patch fixes that by also setting/removing the USB category to the
apps' corresponding GsApp objects.
https://phabricator.endlessm.com/T17097
> flatpak: Fix setting/removing USB category in cached apps

- lib/gs-plugin-loader.c
The installation queue feature is broken from upstream, and while a fix
is on the way, we should disable it for now so we don't have an eventual
number showing up next to the installation tab.
This should be a temporary fix, to be discarded once T21194 lands.
https://phabricator.endlessm.com/T21302
> Disable the saving/loading of the installation queue

- src/gs-application.c
We're completely removing the first run dialog for the moment, to avoid
situations where the dialog is shown more than once. This shouldn't of
course happen, but we need a quick fix and the dialog was not useful in
any case: it adds little value and and delays the loading of the app
tiles.
In the future we may need to revisit this in order to show some useful
information on the first run, and thus this patch keeps toggling the
"first-run" setting, so we have this information in the future.
https://phabricator.endlessm.com/T21725
> Never show the first run dialog

- src/gs-loading-page.ui
The big shopping bag icon in the loading page looks very similar to a
lockpad and this can be confusing for some users. Since we will also
replace the shopping bag icons in the app tiles, the big icon in the
loading page should also be replaced or removed. So for now, we are
removing it.
https://phabricator.endlessm.com/T21925
> Remove the big shopping bag icon from the loading page

- src/gs-updates-page.c
This string is innacurate because e.g. the Flatpak plugin sets the
downloading state even when it's only downloading the AppStream files.
In the future we should fix this properly, by e.g. adding more
download-related status.
https://phabricator.endlessm.com/T22235
> Do not show "Downloading updates" in the updates page

- src/gs-details-page.c
We need to show more directly to users that apps needs to be downloaded,
so we're changing the installation button's label to "Download" but only
if the app is not coming from a removable drive. Otherwise they don't
need to be downloaded, only installed.
https://phabricator.endlessm.com/T21227
> Change the installation button's label to "Download"

- src/gs-application.c
- src/gs-menus.ui
This reverts commit 7625028ed8140e4ea53c1919e05402bef6da508f as the
auto-updates related UI is now part of GNOME Control Center.
https://phabricator.endlessm.com/T22341
> Revert "Add an app menu toggle for turning auto updates on/off"

- plugins/eos/gs-plugin-eos.c
There is a desktop file for providing details about the GNOME System
Monitor app in KDE environments, which was showing up in GNOME Software.
This app should eventually be blocked by checking its project group (set
by the OnlyShowIn key in the desktop file), but this value is being
incorrectly set to GNOME (see [1]) and thus there's no generic way of
hiding the mentioned app. So this patch just blacklists it instead of
setting it as installed, as it does to the rest of the core apps.
[1] https://github.com/hughsie/appstream-glib/issues/236
https://phabricator.endlessm.com/T21451
> eos: Blacklist gnome-system-monitor-kde

- plugins/eos/gs-plugin-eos.c
- plugins/flatpak/gs-flatpak.c
We now have one EknServicesMultiplexer which is required to be installed
whenever we have a knowledge app installed, rather than the previous versioned
EknServices that were dependent on the SDK version being used. This multiplexer
should be installed by the OS, but we want to also pull it in for an upgrade
whenever we're installing a knowledge app as it could be using a new SDK that's
not supported by the old multiplexer.
https://phabricator.endlessm.com/T20936
> T20936: simplify logic for EknServicesMultiplexer & auto-upgrade

- lib/gs-utils.c
The desktop ID given to g_desktop_app_info_new (called from
gs_utils_get_desktop_app_info) needs to have the .desktop suffix. So,
for convenience this patch ensures that the mentioned utils' function
adds the .desktop suffix when the given ID doesn't have it.
https://phabricator.endlessm.com/T22343
> Add the .desktop suffix if needed in gs_utils_get_desktop_app_info

- src/gs-update-monitor.c
This gsetting was used to control whether a refresh should happen on
metered connection, but we're now always allowing metadata refreshes
even on metered connections, since they are important and we're limiting
them to once every 24 hours. For that reason, this patch removes that
setting and its use altogether.
https://phabricator.endlessm.com/T22389
> Remove the refresh-when-metered setting

- src/gs-updates-page.c
The Updates page resets the OS upgrades state to be available again if
there's a change to the updates, or an app removal, etc.. The reason for
this is that package-based systems need to make sure they have all the
packages downloaded, so this would force the user to download any
missing packages.
As a result, if the user has a downloaded OS upgrade in an ostree system,
and restarts GNOME Software, or removes an app, in this state, the OS
upgrade will show the Download button again, even if offline.
Any OS upgrade invalidation should be done by the plugins related to it
and not by the Updates page, so this patch removes the mentioned code.
https://phabricator.endlessm.com/T22503
> Do not invalidate OS upgrades in the Updates page

- plugins/flatpak/gs-flatpak.c
When a runtime was attempted to be installed directly (i.e. not just
because an app was being installed as well), it crashed when getting the
EknServices app for it. The reason is that this function assumed that a
runtime and an app were passed to it, but when installing a runtime, it
is the "app" and its runtime will be NULL.
This patch fixes the mentioned issue by only attempting to get the
EknServices app if a runtime is available.
https://phabricator.endlessm.com/T22523
> flatpak: Only try to get EknServices if an app has a runtime

- plugins/flatpak/gs-flatpak.c
Besides reloading the overview, we should also check if there are
updates coming from USB remotes. This is accomplished by calling
gs_plugin_updates_changed when a USB remote is loaded.
https://phabricator.endlessm.com/T22192
> flatpak: Emit updates-changed when a USB remote is loaded

- src/gs-details-page.c
- src/gs-screenshot-image.c
- src/gs-screenshot-image.h
The details page displays a number of screenshots for regular apps and
it works offline as long as the screenshots have been previously cached.
However, if the screenshots have not been cached, an error screenshot
placeholder is shown instead. This is a problem for many users who are
constantly offline, as most of their apps will display the error
screenshot and thus affect the UX negatively as every app appears to
have an issue.
To help provide a cleaner UX, this patch hides screenshots if they
cannot be loaded when the user is offline. In the process these changes
also refactor the logic around showing the screenshots.
https://phabricator.endlessm.com/T19887
> Refactor screenshots and hide those unavailable when offline

- lib/gs-app.c
@rshuler , I haven't opened a task for this since there's a patch upstream for it already.
> trivial: Fix a small memory leak in gs_app_set_metadata()

- src/gs-overview-page.c
The minimum number of popular apps to be shown was being set to the
maximum allowed, as a result, if an image overrode the popular apps
(using the popular-overrides gsetting) then those weren't being shown.
This patch separates the maximum number of popular apps allowed from
the minimum required.
https://phabricator.endlessm.com/T22925
> Lower the minimum number of popular apps required to be shown

- src/gs-details-page.c
The fallback screenshot placeholder is used when apps don't provide any
screenshots, and should not be shown if the user is offline (because
they will never get an updated AppStream data and thus would always see
the placeholder).
This is in line with the rest of the changes for T19887 that just hide the
screenshots when they fail to load and the user is offline.
https://phabricator.endlessm.com/T19887
> Don't show the fallback screenshot placeholder when offline

- src/gs-updates-page.c
This is very specific to auto-updating which have long list
of pending updates. Mogwai is the actor choosing which update
to schedule next hence, the order cannot be guaranteed.
https://phabricator.endlessm.com/T22556
> Display ongoing app-update at top of the list for easy-visibility

- plugins/flatpak/gs-flatpak.c
If the machine is offline and fetching the metadata results in an error,
simply print a warning, instead of returning the error which results as
an error banner.
This is in order to prevent the very annoying recurring error banner
when e.g. searching, or going into an app's details while offline.
https://phabricator.endlessm.com/T23144
> flatpak: Don't return network-related error on refine if offline

- plugins/core/gs-appstream.c
"GnomeSoftware::popular" kudo has been removed from the build
process[1] due to recent version of appstream-validate started
rejecting that kudo. In order to still keep the logic for getting
"Featured" apps and search-provider relevant, we add this kudo at
runtime while reading the appstream.
[1] https://github.com/endlessm/eos-build/commit/05977432eb2a624a436caedbcb92f9acd41581de
https://phabricator.endlessm.com/T23152
> appstream: Add "GnomeSoftware::popular" kudo to com.endless. apps

- plugins/core/gs-appstream.c
As pointed out in the ticket [1], we actually need to mark our
com.endless apps as GnomeSoftware::popular (at appstream level)
instead of FEATURED_RECOMMENDED (as in commit fc07cef). This is
because appstream's add_popular vfunc populates the popular list
based on GnomeSoftware::popular kudo.
[1] https://phabricator.endlessm.com/T23152
> Mark com.endless apps as popular at appstream level

- lib/gs-plugin-loader.c
- lib/gs-utils.c
- lib/gs-utils.h
In order to adjust the frequency of our update related app-center
notifications, we need to leverage "install-timestamp" first.
Tried to cover these cases (might be missing more of these!):
* App was set to auto-update and it got updated
* An OS upgrade has been done (from updates Tab)
* While clicking on "update all"
* App has been updated from App-details page or  from the Updates
tab's app-row (i.e. it's a user-initiated single app update)
> Set install-timestamp gsetting when we update or upgrade

- plugins/core/gs-appstream.c
- plugins/flatpak/gs-flatpak.c
"GnomeSoftware::popular" kudo has been removed from the build
process[1] due to the recent version of appstream-validate started
to reject that kudo. Now that com.endlessm. apps are not marked
as popular anymore, they are out of the "Featured" list/category
too. In order to still keep the logic for getting "Featured" apps
and search-provider relevant, we explicitly mark com.endlessm. apps
with GnomeSoftware::popular.
[1] endlessm/eos-build@0597743
https://phabricator.endlessm.com/T23152
> Mark com.endlessm. apps as popular when adding to store

- plugins/flatpak/gs-plugin-flatpak.c
- plugins/fwupd/gs-plugin-fwupd.c
- plugins/rpm-ostree/gs-plugin-rpm-ostree.c
https://phabricator.endlessm.com/T23419
Untested, since I haven’t tried to reproduce the bug. This is essentially a drive-by fix.
> T23419 Potential fix for GError crash

- plugins/flatpak/gs-flatpak.c
By default the flatpak create-usb command will search both the user and
system installations for the given refs, and error out if there's
ambiguity and no opportunity for user input (such as when it's being run
in a subprocess of gnome-software). But gnome-software currently only
interacts with the system-wide flatpak installation, so we can use the
--system option when calling flatpak create-usb to prevent ambiguity.
This ensures that the "Copy to USB" feature will work even when remotes
and refs are present in the user flatpak installation (such as happens
when GNOME Builder is run).
https://phabricator.endlessm.com/T20146
> flatpak: Use system installation for create-usb

- src/gs-installed-page.c
Currently, in the "Installed" page, the app whose installation is
in progress and the apps which are queued for installation (marked
as "Pending") are given the same rank while sorting. In this patch,
we change the priority, giving a higher priority to the current
installing app so that it shows at the top, followed by the "Pending"
apps for installation.
This is a partial fix for:
https://phabricator.endlessm.com/T23263
> Display ongoing app-installation at top of the list

- plugins/eos/gs-plugin-eos.c
Apps that are not on the native language of the system will be blacklisted by
gnome-software. Removing this category when it reads from an USB media and
when it verifies if an app is valid fixes the issue.
https://phabricator.endlessm.com/T23409
> flatpak: Remove Blacklisting from USB Apps

- plugins/flatpak/gs-flatpak.c
Currently gnome-software seg faults nearly every time you use the "Copy
to USB" button, especially if the app has already been copied. The copy
happens in a subprocess that is orchestrated by gs_flatpak_app_copy()
which uses copy_process_watch_cb() as the callback function for when the
subprocess exits. However copy_process_watch_cb() sets `helper->finished
= TRUE;` before the end of the function, which causes
gs_flatpak_app_copy() to return and free the GsFlatpakCopyProcessHelper
object. Then copy_process_watch_cb() tries to continue to use the freed
helper object, leading to a segfault in gs_flatpak_refresh(),
specifically in g_hash_table_remove_all().
So this commit fixes the issue by setting helper->finished to TRUE only
at the end of the callback function. An alternative solution …
> flatpak: Avoid a seg fault when copying to USBs

- plugins/flatpak/gs-flatpak.c
There shouldn't be any reason to call gs_flatpak_app_get_copyable()
without passing in a pointer to @copyable, so assert if it's NULL. I've
tested this to make sure the "Copy to USB" feature still works with this
patch.
https://phabricator.endlessm.com/T23651
> flatpak: Assert on programmer error rather than allowing it

- plugins/flatpak/gs-flatpak.c
At the moment gnome-software passes "--system" to the flatpak create-usb
command used to copy apps to USB drives. But this is not necessarily
correct because gnome-software also searches the user installation. So
this commit changes the subprocess call so that it passes the
appropriate option depending on whether the app in question is in a
per-user installation, the default system installation, or another
installation.
https://phabricator.endlessm.com/T23635
> flatpak: Choose correct installation for create-usb command

- src/gs-shell.c
Mask the visibility of "Examine Disk" based on whether "baobab" can be
launched.
https://phabricator.endlessm.com/T21533
> shell: only show "Examine Disk" button when baobab is available

- plugins/flatpak/gs-flatpak.c
This patch fixes a heap-use-after-free of a GError and subsequent seg
fault in the case that you use the "Copy to USB" button and the `flatpak
create-usb` command fails, such as because the `ostree-metadata` ref
isn't available for one of the remotes relevant to the app being copied.
This happens for example if you reflash a computer and never go online
before using the "Copy to USB" feature.
https://phabricator.endlessm.com/T23754
> flatpak: Fix heap-use-after-free of a GError

- plugins/eos/gs-plugin-eos.c
According to our statistics, "[Invalid UTF-8]" is the 3rd most popular
installed app. I also found it in my icon-grid-layout this morning.
Within g_variant_new(), if g_variant_new_string() returns NULL, the
result of g_variant_new_string("[Invalid UTF-8]") is used instead. (This
is the only place in the GLib codebase that this string appears.)
g_variant_new_string() returns NULL only if its argument is NULL, or its
argument fails g_utf8_validate(). Looking in the journal on my system
which has this value in the icon-grid-layout, I see the following:
gnome-software[1569]: g_app_info_get_id: assertion 'G_IS_APP_INFO (appinfo)' failed
gnome-software[1569]: g_variant_new_string: assertion 'string != NULL' failed
and no instances of the g_utf8_validate() assertion failing.
In my case, what …
> eos: fix asking shell to add/remove "[Invalid UTF-8]"

- data/org.gnome.Software.mime.xml
Fix the phrase identifier for a USB with a ostree repo on it to a
more human-readable and upstreamable way.
https://phabricator.endlessm.com/T23777
> translations: Fix Translation for USB with Ostree Repo

- plugins/flatpak/gs-plugin-flatpak.c
Because we re-use code from the appstream plugin, locally-installed Flatpaks
which are loaded from the local AppStream file don't get their pixbuf loaded
unless the icons plugin is run after Flatpak, which means they are considered
invalid and not reliably shown in the Installed tab.
(cherry picked from commit 1fca2bb9a014f3d67f7eeb410d3638e559ba8e43)
Signed-off-by: Robert McQueen <rob@endlessm.com>
https://phabricator.endlessm.com/T20108
> plugins/flatpak: order before icons plugin so icons are loaded

- lib/gs-plugin-loader.c
- src/gs-application.c
- src/gs-details-page.c
- src/gs-shell.c
There were a few different bugs where the shell and the application's idea of whether the shell had finished loading could be bypassed or get out of sync. This branch cleans the shell logic up so that the shell doesn't emit the "loading" signal or leave the LOADING mode until the initial refresh has been completed, and the shell and application can use these guarantees to prevent other actions being started too early.
The main "culprit" here was the USB app installation code reloading the overview page as new mount points appeared, which happens asynchronously during the application startup. This was starting the loading of categories and popular apps before the initial refresh had completed, which was causing live locks between the plugins, and the categories and popular apps staying …
> T23939: fix state tracking/transition around LOADING state

- lib/gs-plugin-vfuncs.h
It had a reference to an `app` parameter that doesn't exist.
> plugins: fix documentation for gs_plugin_os_get_copyable()

- src/gs-application.c
- src/gs-overview-page.c
- src/gs-shell.c
The patch c4579fb dropped from https://github.com/endlessm/gnome-software/pull/423 is actually needed because it prevents the shell from needlessly going to the overview mode before the set_mode GAction is handled - we unconditionally keep the shell_loaded_handler_id as an indicator of whether loading has completed, and the shell decides whether the loading->overview transition is needed or not.
This in turn exposed another bug where if you go from overview to another mode before the categories have loaded, the side filters get shown on the other mode.
https://phabricator.endlessm.com/T23939
> T23939: additional couple of fixes

- src/gs-updates-page.c
Instead of checking that app state != UPDATABLE_LIVE, check that it is
UPDATABLE. This ensures that we don't do a reboot in case of an
unexpected state, such as INSTALLING.
https://gitlab.gnome.org/GNOME/gnome-software/issues/483
(cherry picked from commit c85432c779d76f566eb3e303a1cdaa577ccb3af0)
Signed-off-by: Robert McQueen <rob@endlessm.com>
Moved equivalent code back to to src/gs-updates-page.c where it used to be in
our version.
https://phabricator.endlessm.com/T19785
> updates section: Be more defensive before triggering reboots

- plugins/flatpak/gs-flatpak.c
The updates page needs the signal for refreshing its layout when it has
both PackageKit apps that require reboot, and online updatable flatpak
apps.
This reverts commit 2e7ca21eb2e97468370e6406a47b507d6d7083d1.
This reverts commit 484de32a2843f4e6653d9a1701dac31911a200b1.
(cherry picked from commit befabac6cb5e390022bbeb3deaf852a78a20d2de)
Signed-off-by: Robert McQueen <rob@endlessm.com>
https://phabricator.endlessm.com/T22234
> Revert "flatpak: Stop refreshing the updates page after every update"

- plugins/eos/gs-plugin-eos.c
If an app is:
• Installed
• Blacklisted by the parental controls app filter
• Blacklisted by the parental controls OARS filter
it would only have the QUIRK_PARENTAL_FILTER set on it (from the OARS
filter), but not QUIRK_PARENTAL_NOT_LAUNCHABLE (from the app filter).
This would be fine, but because it’s already installed,
QUIRK_PARENTAL_FILTER is ignored in a few places (correctly); which
makes the lack of QUIRK_PARENTAL_NOT_LAUNCHABLE relevant.
Specifically, it means that the app can be listed in search results, and
on its details page its ‘Launch’ and ‘Add to Desktop’ buttons are
visible and sensitive. They’re supposed to be hidden.
https://phabricator.endlessm.com/T24017
> eos: Ensure both QUIRK_PARENTAL_* quirks can be set simultaneously

- src/gs-details-page.c
Spotted while looking at OpenQA logs for T24855. This is a potential fix
for the following warning:
Jan 28 15:22:57 endless gnome-software[1717]: gs_app_is_installed: assertion 'GS_IS_APP (app)' failed
Spotted by reading the code, rather than any more precise debugging
technique. Other places in gs-details-page.c check (self->app != NULL)
before doing anything with the app, so it’s obviously possible for the
app to be NULL. Guard against that case when updating the ‘Copy to USB’
button too.
https://phabricator.endlessm.com/T24855
> gs-details-page: Possible fix for an assertion failure warning

- src/gs-updates-page.c
The updates page holds a reference to the Mogwai scheduler, which should
normally stop it being invalidated while the page needs it. However, if
some feckless developer runs `systemctl stop mogwai-scheduled`, the hold
on the scheduler will be ignored, and it will disappear from the bus.
Previously, this would cause gnome-software to emit a critical warning
and abort. We probably want it to gracefully drop its scheduler instance
and carry on without scheduling support instead.
Spotted while working on T24117.
> gs-updates-page: Don’t crash if mogwai-scheduled stops

- lib/gs-plugin-loader.c
Restrict G_IO_ERROR_CANCELLED from showing up in the error banner.
Ideally this should not happen as the G_IO_ERROR is converted
to G_PLUGIN_ERROR domain via gs_flatpak_error_convert. Additionally,
this is not reproducable on the upstream gnome-software master as of
now (commit : 5531a7d1).
We should revisit this after gnome-software rebase over 3.32
https://phabricator.endlessm.com/T23928
> fixup! trivial: Never show cancelled error messages to the user

- plugins/flatpak/gs-flatpak.c
When getting the installed apps from Flatpak refs for adding updates,
the code was using the returned GsApp object without checking whether
it's valid. Thus, if that pointer was NULL, it'd not only still keep
using it but also end up reusing an already set GError.
https://phabricator.endlessm.com/T25495
> flatpak: Fix checking installed apps when adding updates

- plugins/eos/gs-plugin-eos.c
This patch adds a couple of comments to code that handdles the proxy
apps to clarify why it touched in some recent changes, though its
functionality should not be changed.
https://phabricator.endlessm.com/T25495
> eos: Clarifying more changes to the existing proxy apps code

- plugins/eos/gs-plugin-eos.c
This state change happens in the function that refines proxy apps, and
ensures that the proxy apps' state is set according to whether it has
apps to be processed; however, especially for developers not very
experienced with GNOME Software, it's good to document why that change
is done the way it is.
https://phabricator.endlessm.com/T25495
> eos: Add a comment clarifying the state change of proxy apps

- plugins/core/gs-desktop-common.c
This category will be used for games developed by Endless Interactive to
highlight them separately from other games.
As of this writing, there are no apps available in this category so it
will not be displayed. However, I've confirmed that the category does
get populated when apps for the associated category are available.
For apps to appear in this category, they will need to include "Endless
Games" in their AppStream <categories>. See the AppStream documentation
for more details:
https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html
This, of course, is an invented category not among the FreeDesktop Menu
Specification's Registered Categories (but it's also not among the
Reserved Categories):
https://specifications.freedesktop.org/menu-spec/latest/apa.html …
> add Learn to Code category

- plugins/eos/gs-plugin-eos.c
- plugins/flatpak/gs-flatpak.c
- src/gs-overview-page.c
Since we moved various applications to Flathub, they fell out of our Featured tab, even though we attempted to update the hard-coded list.
There turned out to be two bugs here:
* The app IDs in the hard-coded list are neither Flatpak app IDs, nor .desktop file IDs: they are the <id> element from the appdata, which may be one or the other.
* We effectively filtered out any app which does not have a tile background image, which (since this is Endless-specific) effectively filtered out any Flathub apps.
Fixing the second point causes Hatch Previewer, a development tool we have published with a com.endlessm.* app ID to Flathub, to appear in the popular app rotation; I addressed this with a nasty special-case. Alternative suggestions welcome!
https://phabricator.endlessm.com/T23953
> Fix displaying Flathub apps on Featured tab

- plugins/flatpak/gs-flatpak.c
Flatpak(v1.3.3) now has a solution to temporary usage of double disk
space for app installs or updates. Therefore, we can undo our 2x free
disk-space factor for updates introduced in [1]. The check for free
disk space against (app's size + min-free-space) needs to be kept
intact.
[1]: https://github.com/endlessm/gnome-software/pull/399
https://phabricator.endlessm.com/T26084
> flatpak: Undo 2x factor in success/failure update heuristics

- plugins/eos/gs-plugin-eos.c
Moving from eos-apps version to Flathub version.
https://phabricator.endlessm.com/T26588
> eos: remove Minecraft from duplicated apps list

- plugins/eos/gs-plugin-eos.c
Add the new toy app com.endlessm.Sidetrack
https://phabricator.endlessm.com/T26622
> eos: update list of proxied apps for the HackComponents

- plugins/eos/gs-plugin-eos.c
This hard-codes filtering of a number of violent and adult-content apps for the Spark personalities.
As a side effect, it bans a few additional violent games for the `gt_GT` personality but I assume that's OK.
I have not tested this myself other than ensuring it builds given a pretty serious time crunch. If it looks good enough, we can merge, build a new Spark image, then test in that
> T26936 spark app filtering

- plugins/eos-blacklist/gs-plugin-eos-blacklist.c
- plugins/eos-blacklist/meson.build
- plugins/meson.build
This splits the blacklist code out of the [`eos` plugin](https://github.com/endlessm/gnome-software/tree/master/plugins/eos) and drops a few bits of it which seem outdated. See the commit messages for rationale, and also see [T26511](https://phabricator.endlessm.com/T26511).
I’ve based this PR on the new `T25367-rebase-in-progress` branch so that only the commits which are relevant to the blacklist are reviewed here. I plan to build up the rebase-in-progress branch with bits of the actual rebase as they get reviewed and merged.
@joaquimrocha, @ramcq, I’ve tagged you two for review because you’ve both had a lot of dealings with these blacklists in the past and can tell me whether some of them still need to stay (or whether more of them can be dropped) than I can.
For context, there’s a big …
> T26511 Split out eos-blacklist plugin from eos plugin

- plugins/eos/gs-plugin-eos.c
Moving from eos-apps version to Flathub version.
https://phabricator.endlessm.com/T26658
> eos: remove Scratch from duplicated apps list

- debian/changelog
- debian/control
- debian/control.in
* Drop Debian-specific dependencies (T25367)
- libgtk3-perl: Needed for debconf
- software-properties-gtk: Debian-specific apt repository configuration tool
* Drop fwupd `recommends` line (T25367)
- We already dropped the build dependency, so keeping the `recommends` is
just confusing.
* Drop `apt-config-icons` dependency (T25367)
- Our apt repositories don’t support it, and the majority of our apps are
packaged in flatpak.
https://phabricator.endlessm.com/T25367
> debian: Drop Debian-specific dependencies

- plugins/eos/gs-plugin-eos.c
- plugins/flatpak/gs-flatpak.c
- plugins/flatpak/gs-plugin-flatpak.c
- src/gs-background-tile.c
- src/gs-updates-section.c
Some fixes for various critical warnings I’ve seen while playing around with gnome-software now the rebase has landed.
No associated Phab task.
Includes two commits cherry-picked from upstream:
* https://gitlab.gnome.org/GNOME/gnome-software/commit/bc855b242ceedebc224a2e44a47512728cbd31cf
* https://gitlab.gnome.org/GNOME/gnome-software/commit/ad93551b8661429895b448a1e3766c877c2eac4c
> Misc post-rebase fixes

- plugins/flatpak/gs-flatpak.c
This function transfers the ownership of the memory to the caller
code which was not freeing it.
https://phabricator.endlessm.com/T15300
> Fix leaks when using flatpak_remote_get_url

- src/gs-updates-section.c
When an app is in the middle of its installation phase of doing an
update, and you click its row in the updates page to switch to its
details, then click the ‘back’ button to return from the details page to
the updates page, gnome-software will crash with the following assertion
failure:
```
gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
**
Gtk:ERROR:../../../../gtk/gtkwidget.c:12348:gtk_widget_real_map: assertion failed: (_gtk_widget_get_realized (widget))
```
The widget in question is the GsUpdatesSection.section_header, which had
somehow ended up with no parent widget, but still being iterated over in
the realize loop for the GsUpdatesSection.
The code in `_list_header_func()` to remove it from the
`GsUpdatesSection` may have caused this; …
> gs-updates-section: Avoid crash when switching modes

- plugins/eos/gs-plugin-eos.c
eos: Set services apps GsApp information correctly
The bug was discovered when testing out the search functionality
for the new gnome-software-3.32. There was something inherently
wrong with searching knowledge apps with queries like:
* com.endlessm.
* health
* animals
* teeth
and so on...
After some digging and looking at the --verbose log, it was found
that the appropriate search results where added to the GsAppList
(in the --verbose log) but could not be seen on the search page.
A few more steps in exploration, it was found that the endlessm
apps specifically where getting refined using gs_plugin_refine_wildcard
while other apps, mainly from flathub and gnome-apps-nightly
where getting refined using gs_plugin_refine during the search.
Hence, next step was to found out where these …
> fixup! eos: Add EknServicesMultiplexer as a related app for EKN apps

- lib/gs-app.c
Set the entire metadata GVariant instead of setting each metadata
component as a string value. The reason is some metadata components
are not GVariant strings (e.g. "flatpak::RefKind"). Subsuming
such a component will throw a critical as:
```
07:02:57:0442 GLib g_variant_get_string:
assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_STRING) ||
g_variant_is_of_type (value, G_VARIANT_TYPE_OBJECT_PATH) ||
g_variant_is_of_type (value, G_VARIANT_TYPE_SIGNATURE)' failed
```
for gs_app_get_metadata_item.
(Backported from e0bab44f941cb44f93d5309d7a5e336df46ce07b upstream)
> lib/app: Set entire metadata GVariant in gs_app_subsume_metadata

- src/gs-updates-section.c
This reverts commit 12e48ce81af4bce099cd09d2b535404d04cfd41c.
It doesn’t solve the bug and crashes still occur — it is obviously not
the right fix, and has not been accepted upstream.
https://phabricator.endlessm.com/T27333
> Revert "gs-updates-section: Avoid crash when switching modes"

- plugins/core/gs-appstream.c
This reverts commit 7af0a22975b972f5e5b2ee94c219bb62ab0b5ccc.
Drop this patch as it wasn't a systematic fix for the problem.
Also, the upstream has introduced a way to subsume metadata from
the wildcard to a real concrete GsApp [1], and the UI is rendered
with the real app + wildcard's extra-metadata (for e.g. marked popular,
extra categories). Hence, the problem of two objects out-of-sync
for a single app doesn't seem to be a case any longer.
The revert has been tested with gnome-3.32 rebase and there was
no issue of two objects having different app state were observed
during the test.
This patch all the more made hard to mark apps popular via external
appstream (T26507), as the apps created by gs_appstream_add_popular
were not necessarily marked as wildcards. It was only marked as …
> Revert "Use the global cache when creating popular apps by appstream"

- plugins/core/gs-appstream.c
This reverts commit ed922ffc66ab1e400c415d40934d059bde9a408a.
Popular apps are now marked via external-appstream. We don't need to
hard code to mark Endless-specific apps as popular.
Any app from any remote can be marked as popular now, with the help
of external-appstream(i.e. eos-extra.xml)
See https://github.com/endlessm/gnome-software-data/pull/15/
https://phabricator.endlessm.com/T26507
> Revert "eos: Mark com.endless. app as GS_APP_KUDO_FEATURED_RECOMMENDED"

- src/gs-overview-page.c
This was a rebase failure caused by 6e8cd654d2 not deleting the old code
(so changes rebased into that code weren’t noticed as part of the
rebase due to not causing conflicts).
When this is next rebased, commit 6e8cd654d2 should be modified to drop
the unused code, and this commit squashed into subsequent commits.
https://phabricator.endlessm.com/T26770
> gs-overview-page: Fix the USB category in the sidebar

- lib/gs-self-test.c
- lib/meson.build
- plugins/core/gs-plugin-appstream.c
- plugins/flatpak/gs-plugin-flatpak.c
As discussed from the standup call, we start to backport fixes from upstream merge-requests which are blocked on current maintainer's review. These commits look safe and hence we decided to move forward with it.
* "appstream: Also query the real appdata files during refine …" - [upstream merge request](https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/306)
* "flatpak: Fix logic error check of GsFlatpak in gs_plugin_download …" - Already [merged](https://gitlab.gnome.org/GNOME/gnome-software/commit/3e1fe203b40248f571be2a804027acd8e23dc54e) upstream
> Backport fixes for T27438 and T27668

- plugins/flatpak/gs-plugin-flatpak.c
Unfortunately 68110bf345e38b69f7b4ddf09990be3b53074766 meant that an incorrect early return was replaced by a `NULL` pointer dereference since later in the function, `flatpak` is assumed to be non-`NULL`. This manifested itself in gnome-software segfaulting in the cases where it would previously have silently failed to install any Flatpaks:
```
(gdb) bt 
#0  gs_flatpak_get_installation (self=self@entry=0x0) at ../plugins/flatpak/gs-flatpak.c:3521
#1  0x00007fffdf23d49f in gs_flatpak_has_space_to_update (flatpak=flatpak@entry=0x0, list=list@entry=0x555557120180, 
is_auto_update=is_auto_update@entry=1) at ../plugins/flatpak/gs-plugin-flatpak.c:546
#2  0x00007fffdf23e306 in gs_plugin_download (plugin=plugin@entry=0x55555592bb20, list=list@entry=0x7fffcc093980, …
```
> Fix NULL pointer dereference in flatpak gs_plugin_download()

- src/gs-shell.c
Just as we ignore `GS_PLUGIN_ERROR_CANCELLED` errors, ignore
`G_IO_ERROR_CANCELLED` errors.
Realistically, we are never going to manage to find every call site
which could return `G_IO_ERROR_CANCELLED` and convert all of those
errors to `GS_PLUGIN_ERROR_CANCELLED` on an ongoing basis.
---
This is a trivial cherry-pick from [an upstream MR](https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/322) I submitted today to squash some console warnings. It’s not associated with a particular Phabricator task, but there have been related tasks about squashing ‘cancelled’ warnings in the past.
> shell: Ignore G_IO_ERROR_CANCELLED errors

- lib/gs-self-test.c
- lib/meson.build
- plugins/core/gs-plugin-appstream.c
- plugins/flatpak/gs-flatpak.c
This PR basically backports the patches for T27779. The earlier commit 
6aaada0 can also be reverted as it was not accepted [upstream](https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/306) and was superseded by this [merge request](https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/320) (which we are backporting).
Also included a simple typo fix in the backport. 
https://phabricator.endlessm.com/T27779
> Backport patches for T27779

- src/gs-shell.c
- src/gs-updates-section.c
See https://phabricator.endlessm.com/T27333#760980.
This is a trivial backport of https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/299, and another patch to fix a warning with category testing which isn’t applicable upstream.
> T27333 Partial fix for crash on updates tab

- plugins/flatpak/gs-flatpak-transaction.c
- plugins/flatpak/gs-flatpak-transaction.h
- plugins/flatpak/gs-plugin-flatpak.c
- plugins/flatpak/gs-self-test.c
- src/gs-update-monitor.c
See https://phabricator.endlessm.com/T27438#760799
These patches seems to me in a pretty good shape but still lacking upstream review as of now. 
These are cherry-picked from upstream's merge-requests as mentioned in the above phabricator link.
Ideally, we should backport them after merging them upstream but that probably will miss the hard-code freeze. 
I have been interactively tested these patches for autoupdates code path and made sure that the apps update reliably, pointing to the latest flatpak commit. This is one of the major issues of  T27438 as [noticed](https://phabricator.endlessm.com/T27438#758602) by me and Will. 
I have included the commit "updates monitor: Don't skip automatic updates that require new permission"  (which is basically a revert of cc6f8df) because I have …
> T27438 - Flatpak apps autoupdates

- lib/gs-app-list-private.h
- lib/gs-plugin-job.c
- plugins/core/gs-appstream.c
This PR also fixes another warning when refining an app with <content_rating> without the "type" attr set (note that this commit is not really needed to fix the crash):
```
22:32:03:0210 GLib g_str_has_prefix: assertion 'str != NULL' failed
```
https://phabricator.endlessm.com/T28074
> Fix crash when switching categories on ARM

- plugins/core/gs-appstream.c
- plugins/core/gs-plugin-appstream.c
This fixes the problem of system installed apps not appearing
in their relevant categories as mentioned in their appdata.
These apps are marked as wildcards by gs_appstream_add_category_apps,
hence the refine function for wilcards should also match the real
GsApp using the appdata query.
https://phabricator.endlessm.com/T27899
https://phabricator.endlessm.com/T27505
> Show system apps in their relevant categories

- plugins/flatpak/gs-flatpak.c
Fixup <metadata> tag to <custom> for appstream versions >= 0.9.
Appstream plugin already does this for it's appstreams' xmlb
silos via gs_plugin_appstream_upgrade_cb hence, flatpak
plugin should also follow it.
(Manually cherry-picked from upstream commit
22dd273fab2145dd4564e8c97cc336bc1dcbc93b)
https://phabricator.endlessm.com/T28093
-----
Note: Needed a manual cherry-pick of code, as git cherry-pick was conflicting.
Upstream MR: https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/341
> flatpak: Fixup <metadata> tag to <custom>

- plugins/eos-blacklist/gs-plugin-eos-blacklist.c
- plugins/eos-blacklist/meson.build
Make eos-blacklist avoid blacklisting apps that ends with a specific
set of locales dictated by the flatpak user's configuration file.
https://phabricator.endlessm.com/T24213
~** Only merge-able after https://github.com/flatpak/flatpak/pull/3058~
~** Only merge-able after the flatpak rebase~
~** Only merge-able after https://github.com/flatpak/flatpak/pull/3152~
> eos-blacklist: Allow multiple locales for g-s apps

- plugins/odrs/gs-plugin-odrs.c
Kodi (tv.kodi.Kodi) segfaulted the entire gnome-software when trying
to install it via flatpak. This was due to the fact that one of
the reviewer's id was essentially NULL. Hence, don't add reviews
whose reviewer-id is NULL.
https://phabricator.endlessm.com/T28338
> odrs: Only add reviews from non-NULL reviewer's id

- plugins/eos-blacklist/gs-plugin-eos-blacklist.c
Migrated to Flathub.
https://phabricator.endlessm.com/T28386
> eos-blacklist: remove Etoys entry from duplicates list

- lib/gs-plugin-loader.c
This fixes an issue when switching categories in a quick succession where `gs_plugin_loader_job_process_async()` is invoked for a category, then gets cancelled before completing when the category is changed but the thread running the initial job still returns a valid result, which then confuses GsCategoryPage which ends up re-adding the items.
**Note**: I am not sure if the issue is on Glib itself, given `gs_plugin_loader_job_process_async()` sets `g_task_set_check_cancellable (task, FALSE)` and `g_task_set_return_on_cancel (task, FALSE)`, but doesn't check if the task was cancelled before returning a valid result.
Note also that the thread doing the initial async job (`gs_plugin_loader_process_thread_cb()`) already checks the cancellable in a few places, but then proceeds to do other …
> gs-plugin-loader: Only return success if task hasn't been cancelled yet

- lib/gs-plugin-loader.c
With the introduction of adedc2e09 the plugin jobs started to actually
get cancelled when requested, instead of returning a valid result
even though they got cancelled.
This introduced a new issue where if the plugin loader times out (which
in turn cancels the current operation) while loading a category we end up
with an empty list of tiles (which are created as placeholders before the
load operation finishes).
This happens because now we respect the cancellation request and return
an error when the operation gets cancelled, opposed to the way it was before
where a valid result could still be returned even though the operation was
cancelled.
As a workaround to fix this issue we are now removing the timeout, given
we don't want cancelled operations to return valid values and neither show …
> HACK: Disable timeout for plugin job operations

- plugins/flatpak/gs-flatpak-transaction.c
- plugins/flatpak/gs-plugin-flatpak.c
In T28302, due to encyclopedia split between
com.endlessm.encyclopedia.en and com.endlessm.encyclopedia.en.Content,
old versions of encyclopedia (under one ref) didn't get the
content ref when they tried to upgrade the app. Hence, encyclopedia
broke for those users as there was no content ref.
The content ref is a related ref. Flatpak changes [1] can detect if
such a related ref is missing on the installation and therefore,
can mark the app as updatable again.
We need to make sure that gnome-software can be aware of this state
and sync the main app and related app's states accordingly for UI/UX.
[1] https://github.com/endlessm/flatpak/pull/197
https://phabricator.endlessm.com/T28302
> transaction: Sync main app's state if a related ref is installed

- plugins/flatpak/gs-flatpak-transaction.c
Built on top of solution of https://github.com/endlessm/gnome-software/pull/512
(See also base branch)
---
Flatpak changes [1] will start marking apps as updatable if their
runtime component is missing on the installation. These apps will
be shown as updatable in gnome-software updates panel but in the
background they are meant to fetch their missing runtime.
Since many apps can target one runtime, the absence of that runtime
can make many apps show up in the updates panel. In that case,
check if the runtime is downloaded → installed and set all
apps' state back to "installed". This solves the case
if users chooses to click "Update All".
[1] https://github.com/flatpak/flatpak/pull/3204
https://phabricator.endlessm.com/T27077
---
* Single Manual update :heavy_check_mark: 
* Autoupdates …
> transaction: Sync installed apps' state missing runtime is re-installed

- plugins/flatpak/gs-flatpak-transaction.c
Flatpak may set the "estimating" flag on a progress report if the value
is bogus, or it may set it if it is downloading metadata which it
arbitrarily decides comprises the first 5% of an install operation.
Ignoring estimated progress therefore means we get no progress changes
for the first 10% of an app install (installing the app and its locale
extension). Instead, only ignore the estimated progress if it is an
obviously bogus value of >10%.
https://phabricator.endlessm.com/T28764
> flatpak: Only ignore estimated progress if >10%

- plugins/eos/gs-plugin-eos.c
- plugins/flatpak/gs-flatpak-transaction.c
- plugins/flatpak/gs-flatpak-transaction.h
- plugins/flatpak/gs-plugin-flatpak.c
Tested locally by downgrading both `EknServicesMultiplexer` and `quote_of_the_day`. The updates are showed in the `Updates` tab grouped in the `Endless Platform` proxy app and clicking `Update` on it actually updates the proxied apps as expected.
https://phabricator.endlessm.com/T28672
https://phabricator.endlessm.com/T29298
> Fix proxy apps updates support

- src/gs-details-page.c
When checking for updates, the plugin status will change. If that
happens before an app detail page is first viewed by the user (which is
a common situation if gnome-software is started in the background and
does a background update check), a load of `gs_app_*()` methods will be
called on `self->app` when it is `NULL`, giving a load of critical
warnings.
Avoid that by doing what every other call site of
`gs_details_page_refresh_all()` does, and checking whether `self->app ==
NULL` first.
> gs-details-page: Avoid a NULL object dereference

- src/gs-details-page.c
This reverts commit 9ec0926b06793eb8b51cfd7af096ced4cdc05695.
When we next rebase, this commit and the commit it reverts can both be
dropped.
The appdata generation code has been fixed to either generate licenses
correctly or not at all, and hence it’s no longer harmful to show the
license in gnome-software.
https://phabricator.endlessm.com/T12886
> Revert "Hide the license details in the details page"

- plugins/eos-updater/gs-plugin-eos-updater.c
- plugins/eos-updater/meson.build
Submit a metrics event containing the current state of the parental
controls for the current user whenever a poll happens for OS updates.
This will give us an overview of whether parental controls have been
enabled by our users.
The choice of submitting it when polling for OS updates was fairly
arbitrary: we needed a regular submission event which was independent
from the parental controls being edited. See T28741 for details.
This commit should not be upstreamed.
https://phabricator.endlessm.com/T28742
---
Debian changes in #534.
> eos: Add parental controls metrics on update poll

- plugins/malcontent/gs-plugin-malcontent.c
Trivial backport of https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/436.
https://phabricator.endlessm.com/T29286
> T29286 Fix re-filtering apps when parental controls app filter changes

- src/gs-category-page.c
Revert two patches from https://phabricator.endlessm.com/T22807 whose caching behaviour was somehow causing duplicate apps to appear when refreshing a category. The same performance improvements should be gained by improving upstream performance (but this PR doesn’t do that, so it causes a performance regression, adding about 2s to each category load).
https://phabricator.endlessm.com/T29286
> T29286 Fix duplicate apps when refreshing category

- plugins/flatpak/gs-flatpak.c
In gs_flatpak_set_kind_from_flatpak(), we use AS_APP_KIND_LOCALIZATION
and AS_APP_KIND_GENERIC in addition to AS_APP_KIND_RUNTIME, all for
things which from Flatpak's perspective are runtimes (their ref starts
with "runtime/"). So change checks in a few places to correctly identify
Flatpak runtimes instead of checking for AS_APP_KIND_RUNTIME, which has
the effect of ensuring that applications properly show as needing an
update when their locale extension needs an update, e.g. because the
user chose a language other than the one the locale extensions already
have.
https://phabricator.endlessm.com/T24168
> flatpak: Properly check if an app is a runtime

- plugins/eos-blacklist/gs-plugin-eos-blacklist.c
As with so many of these, the blacklist is completely ineffective
because when it was ultimately added to Flathub, the app ID was
different (lowercase 'f' in 'org.mozilla.firefox').
I haven't even compiled this because there is nothing to test. The Flathub version is already visible, crap metadata and all.
https://phabricator.endlessm.com/T29746
> eos-blacklist: unblacklist Firefox from Flathub

- plugins/flatpak/gs-flatpak-transaction.c
This can be dropped when we rebase to flatpak ≥ 1.7.3 on Endless OS.
Until then, change the version checks in `GsFlatpakTransaction` to use
the new libflatpak progress APIs which we backported to flatpak 1.6.2.
https://phabricator.endlessm.com/T29774
> flatpak: Endless-only change to depend on backported flatpak APIs

- plugins/eos-blocklist/gs-plugin-eos-blocklist.c
- plugins/eos-blocklist/meson.build
- plugins/meson.build
Replace usages of the terms whitelist and blacklist in our downstream
code with the more inclusive and precise terms allowlist and blocklist.
The only functional change here is that the .so file for the plugin is
renamed, but this does not necessitate any packaging change since we
match "*.so" in debian/gnome-software.install.
The corresponding upstream MR is here:
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/475
https://phabricator.endlessm.com/T30329
> eos-blacklist: Rename to eos-blocklist

- lib/gs-app.c
- lib/gs-metered.c
- lib/gs-plugin-loader.c
- lib/gs-self-test.c
- lib/gs-test.c
- lib/gs-test.h
- meson.build
- meson_options.txt
- plugins/core/gs-plugin-icons.c
- plugins/core/gs-self-test.c
- plugins/dpkg/gs-self-test.c
- plugins/dummy/gs-self-test.c
- plugins/fedora-langpacks/gs-self-test.c
- plugins/flatpak/gs-self-test.c
- plugins/fwupd/gs-self-test.c
- plugins/modalias/gs-self-test.c
- plugins/packagekit/gs-self-test.c
- plugins/repos/gs-self-test.c
- plugins/snap/gs-self-test.c
- src/gs-self-test.c
Make the CI execute unit tests rather than merely building
gnome-software for downstream PRs. In T29985 I landed fixes for the
flatpak extension unit tests and that brought this issue to light.
This commit can be squashed into "build: Override meson's default
options" during the next rebase.
https://phabricator.endlessm.com/T21809
> build: Enable unit tests for CI

- debian/rules
Setting -Dtests=true isn't enough to enable the unit tests in OBS builds
(as I did in the last commit). We also need to avoid overriding
dh_auto_test.
https://phabricator.endlessm.com/T21809
> debian: Ensure tests are actually run

- plugins/flatpak/meson.build
The flatpak self tests currently only work on x86_64. See
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1047
https://phabricator.endlessm.com/T21809
> flatpak: Skip self tests on arm

- lib/gs-app-list-private.h
- lib/gs-plugin-job.c
This reverts an upstream commit that was based on one of our downstream patches for 3.7 but that still causes the crash and re-applied the original patch from 3.7 which fixed the issue for me.
NOTE: Do not merge this just yet as we are on freeze.
https://phabricator.endlessm.com/T30658
> Fix ARM crash when switching categories

- plugins/flatpak/gs-plugin-flatpak.c
This commit fixes offline installation of .flatpak bundles, and fixes
offline installation of .flatpakref files that point to a file:// URL.
Currently such installations would be forever stuck in the "Pending
installation..." state. The check for a file:// prefix on the
gs_app_get_origin_hostname() return value is wrong because in case a
file:// URL is set, "localhost" is returned. See gs_app_func() in
lib/gs-self-test.c.
One might wonder if this could be implemented by checking if
gs_app_get_local_file() returns a non-NULL value, but
gs_app_set_local_file() is called for flatpakref files which are not
always offline friendly.
https://phabricator.endlessm.com/T30749
> flatpak: Fix offline installation

- lib/gs-plugin-loader.c
- plugins/core/gs-appstream.c
Trivial backport of https://gitlab.gnome.org/GNOME/gnome-software/-/commit/a93ae7330f and https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/521 to improve error handling of failed downloads.
https://phabricator.endlessm.com/T30217
> T30217 appstream error handling

- debian/changelog
- debian/control
- debian/control.in
- debian/rules
- Enable fwupd
- Enable libfwupd-dev
Signed-off-by: Jian-Hong Pan <jian-hong@endlessm.com>
https://phabricator.endlessm.com/T29506
> debian: List available firmware updates in gnome-software

- debian/changelog
- debian/control
- debian/control.in
- debian/rules
Reverts endlessm/gnome-software#532
https://phabricator.endlessm.com/T29506
> Revert "debian: List available firmware updates in gnome-software"

- plugins/flatpak/gs-plugin-flatpak.c
When constructing the update transaction, tell flatpak that it can clean
up unused EOL runtimes during the transaction.
We don't have any UI for that, which hopefully should be fine.
Note from downstream cherry-pick: Changed Flatpak version check from
1.9.1 to 1.8.2, since we backported the relevant Flatpak API:
https://github.com/endlessm/flatpak/pull/241
(cherry picked from commit b01c36b7509c336ba628c76e2d08b3f88a63d310)
https://phabricator.endlessm.com/T22790
> flatpak: Use new flatpak API to automatically remove EOL runtimes

- plugins/flatpak/gs-plugin-flatpak.c
If adding an update to the transaction fails, skip it rather than
failing the whole update operation. This gives a chance to successfully
update other apps.
This is what the command line `flatpak` tool does.
---
Trivial cherry-pick from https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/520
https://phabricator.endlessm.com/T30233
> flatpak: Skip updates which fail

- lib/gs-app.c
- lib/gs-app.h
- plugins/flatpak/gs-flatpak-transaction.c
- plugins/flatpak/gs-flatpak.c
- src/gs-app-row.c
https://phabricator.endlessm.com/T31068
> T31068 Support renaming Flatpaks

- plugins/eos-blocklist/gs-plugin-eos-blocklist.c
We are removing all web links from the OS, let's remove the special handling here also.
Depends on whether we are also dropping image personalities' specific web links - see https://github.com/endlessm/eos-image-builder/pull/975.
https://phabricator.endlessm.com/T31560
> eos: Remove eos-link-* special handling from blocklist

- src/gs-page.c
This is a trivial backport of https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/666 from upstream, plus an additional commit to do the same to the USB operations, which are not yet upstream.
https://phabricator.endlessm.com/T31351
> T31351 Correctly set interactive status for various operations

- plugins/eos/gs-plugin-eos.c
Since adding the upstream Debian repositories to our apt configuration,
`appstreamcli refresh-cache` has been pulling in appstream for all the
Debian repositories, via the configuration in
`/etc/apt/apt.conf.d/50appstream`.
This appstream data includes many applications which are available in
apt but which are not installed on the image. It also includes a few
applications which are installed on the image and which aren’t removable.
Previously, when this data was unavailable, the `eos` plugin in
gnome-software could safely assume that all non-flatpak apps were built
in to the image, and hence were both installed, and compulsory.
That situation has now changed, so change the logic to:
* Mark any non-flatpak app as compulsory (not uninstallable) if it’s
installed.
* Hide any other …
> eos: Stop marking all non-flatpak apps as installed and compulsory

- plugins/flatpak/gs-flatpak.c
- src/gs-app-row.c
- src/gs-updates-section.c
This is the result of:
```
$ git cherry-pick c0a287cd7620274010fda1e9b998bb41ec610bb5 a9f1143e900632ed57eabe2da11f684cf0418972 c28636404e36ee6b8d6a0a06474a70aa26aafe5b
Auto-merging plugins/flatpak/gs-flatpak.c
[T31562-38-update 02e008781] flatpak: Fix assertation in new libflatpak version
Author: Richard Hughes <richard@hughsie.com>
Date: Mon Feb 8 09:56:55 2021 +0000
1 file changed, 1 insertion(+), 1 deletion(-)
Auto-merging src/gs-app-row.c
[T31562-38-update 781b7c8bc] app row: Avoid emitting "unrevealed" signal when in destruction
Author: Kalev Lember <klember@redhat.com>
Date: Tue Oct 13 16:46:11 2020 +0200
1 file changed, 5 insertions(+)
Auto-merging src/gs-updates-section.c
Auto-merging src/gs-app-row.c
[T31562-38-update 13532dac0] gs-updates-section.c: destroy() rows rather than …
```
> T31562 Cherry-pick some patches from gnome-3-38 branch

- debian/control
- debian/control.in
The build is failing with:
```
msgfmt: cannot locate ITS rules for data/org.gnome.software.external-appstream.policy.in
```
This is because the ITS rules come from policykit-1 and the translations
can't be completed without them. This was fixed in Debian in 3.38.0-2.
https://phabricator.endlessm.com/T30746
> Add build dependency on policykit-1

- plugins/flatpak/gs-self-test.c
This is currently breaking ostree builds. Let's temporarily disable
failing tests so we can continue working on other high priority tasks
while they get fixed properly.
https://phabricator.endlessm.com/T32793
> [DROP-ME] tests: Temporarily disable failing tests

- meson.build
- plugins/flatpak/gs-self-test.c
This uses upstream flatpak's environment variable to skip parental controls rather than our downstream environment variable that was recently removed. I tested this in OBS and it succeeded. I believe the 2nd commit is a candidate for upstream gnome-software (at least until malcontent mocking is written or there's some other non-dbus method to skip parental controls).
https://phabricator.endlessm.com/T32793
> Better flatpak skip parental controls

- plugins/eos-blocklist/gs-plugin-eos-blocklist.c
Our App Center has a hardcoded list of Flatpak apps to hide because they are built into the OS. When we move an app from the OS to a Flatpak, we need to update this list so the App Center will show the Flatpak version.
Remove -GNOME Calculator and Gedit from this blocklist.
https://phabricator.endlessm.com/T32879
https://phabricator.endlessm.com/T32906
> Remove Calculator and gedit from blocklist

- debian/rules
While we don’t want the snap plugin to be installed or enabled on EOS,
the Debian packaging has now been changed (upstream in Debian) to build
the snap plugin as a separate package, which we can just not install on
EOS.
Explicitly disabling the plugin causes that package to fail to build.
This can be squashed into the commit to apply Endless-specific packaging
changes next time we rebase.
https://phabricator.endlessm.com/T32854
> debian: Stop disabling Snap in EOS build

- debian/gnome-software.install
These are enabled on EOS by `-Dexternal_appstream=true`, but are not
enabled in the default Debian packaging.
https://phabricator.endlessm.com/T32854
> debian: Distribute external-appstream files

- debian/control
- debian/control.in
- libgtk3-perl: Needed for debconf
- software-properties-gtk: Debian-specific apt repository configuration tool
- apt-config-icons: Needed to show icons for apps to be installed with apt
- packagekit: It's packagekit!
None of these are relevant on Endless OS where apps cannot be installed
with apt.
This is spiritually a cherry-pick of
683c20c33345a8fd9fe8620e42b35fec0e75987c.
https://phabricator.endlessm.com/T32854
￼
> Move 3 dpkg/apt-related packages to Suggests:

- plugins/eos-blocklist/gs-plugin-eos-blocklist.c
We have removed this from the OSTree and ship the Flatpak instead.
https://phabricator.endlessm.com/T32983
> eos-blocklist: Remove GNOME Contacts from blocklist

- debian/rules
There has never been an 'ostree' option, though there was an
'enable-ostree' option prior to 3.28.
Meson 0.60.1 makes providing unknown options fatal.
This can be squashed into the commit to apply Endless-specific packaging
changes next time we rebase.
https://phabricator.endlessm.com/T33213
> debian: Don't provide nonexistent option to meson configure

- lib/gs-plugin-loader.c
The installation of pending apps is handled by GsInstalledPage usually, which refines the app list before actually installing them. However, there is an alternative code path in GsPluginLoader that doesn't refine, and yet tries to install the pending apps queue.
Not refining the pending apps list is risky, since the Flatpak plugin needs to add metadata to the app in order to proceed with installation.
Refine the pending apps queue before installing it.
https://phabricator.endlessm.com/T33188
> plugin-loader: Refine before installing pending apps

- lib/gs-plugin-job-list-apps.c
(Plain, zero-conflict backport of https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1508)
This filtering was lost with 7d54958d4e46e27af2cbdfc7f529611f4709d7fe.
Filter out invalid apps as it did before.
Closes https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1932
https://phabricator.endlessm.com/T33889
> gs-plugin-job-list-apps: Filter out invalid apps

- plugins/eos/gs-plugin-eos.c
Previously we assumed that everything that is not a Flatpak (or the OS
itself, which can be upgraded) is either built-in (if it is installed)
or cannot be installed (if not).
Since the reintroduction of web-app support in GNOME Software, this is
no longer true: web apps can be installed if not already installed, and
removed if installed. Skip them when marking apps as compulsory or
hide-everywhere.
https://phabricator.endlessm.com/T19646
> eos: Don't hide web-apps or mark them as unremovable

- lib/gs-app.c
- plugins/eos-updater/com.endlessm.Updater.xml
- plugins/eos-updater/gs-plugin-eos-updater.c
- plugins/eos-updater/tests/eos_updater.py
Trivial backport of https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1567 to EOS `master`.
This will need fast-forwarding to on `eos5.0` once landed, and then backporting to `eos4.0`. I haven’t done that yet as there are a couple of other backports waiting review and it’s getting to the point where a merge train would be needed if I added more PRs.
> T34082 Backport ‘Learn More’ link changes for upgrades from upstream

- plugins/eos-updater/com.endlessm.Updater.xml
- plugins/eos-updater/gs-plugin-eos-updater.c
- plugins/eos-updater/tests/eos_updater.py
Backport of https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1555 to EOS 4. There were quite a few cherry pick conflicts to resolve, but almost all of them were superficial (API renames, better use of GObject, etc.)
Compile tested only.
https://phabricator.endlessm.com/T34184
> T34184 Backport major/minor update UI to EOS 4

- lib/gs-os-release.c
- lib/gs-os-release.h
- plugins/eos-updater/gs-plugin-eos-updater.c
Just like using an app icon to brand the updates for an app, this makes it a bit more obvious what the updates are.
(Backport 4.0: Rework code in eos-updater plugin as the control flow is significantly different in eos4.0 vs eos5.0.)
Upstream: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1556 https://phabricator.endlessm.com/T33143
> eos-updater: Use the OS logo for minor update rows (backport to eos4.0)

- lib/gs-app.c
- plugins/eos-updater/com.endlessm.Updater.xml
- plugins/eos-updater/gs-plugin-eos-updater.c
- plugins/eos-updater/tests/eos_updater.py
Non-trivial backport of https://github.com/endlessm/gnome-software/pull/607 to `eos4.0`.
I had to pull two more commits in from GNOME 41 to get the `GsApp:urls` property in a suitable state to cherry-pick the actual changes onto. After that, the cherry pick conflicts were trivial.
https://phabricator.endlessm.com/T34292
> T34292 Backport ‘Learn More’ link changes for upgrades to eos4.0

- src/gs-updates-page.c
Image based OS updates, which need a restart to be applied, should always be labelled as needing a restart.
While that would happen OK if gnome-software added them to the updates page when eos-updater is polling or ready, if they were added to the page when already being fetched (or in subsequent states of eos-updater), the `GsApp` for the update would be in the `GS_APP_STATE_INSTALLING` state, and this would trigger the updates page to add the update to the wrong section.
Fix that by always putting OS updates which need a reboot into the `OFFLINE` section.
Upstream: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1588
Fixes: #2028, #2038
> gs-updates-page: Ensure correct section is used for minor OS updates

- debian/rules
We're going to consume the current webapp lists into our own external appstream and don't want duplicates from the hard coded lists.
https://phabricator.endlessm.com/T34569
> debian: Disable hardcoded webapps

- plugins/flatpak/gs-plugin-flatpak.c
Previously the code tried to not return an error to the user if
automatic updates failed in the background due to a lack of disk space.
However, by returning `TRUE` from `gs_plugin_flatpak_update()`, this
signalled success for the updates, which would result in a “123
Applications Updated” notification banner which was completely
incorrect.
Instead, it’s better to return an error, and then let the UI layer
determine whether to display that as a massive warning dialogue, a small
in-app warning notification, or not at all.
https://phabricator.endlessm.com/T33138
> T33138 flatpak: Don’t signal success for automatic updates if not enough space

- lib/gs-os-release.c
- lib/gs-os-release.h
- plugins/eos-updater/gs-plugin-eos-updater.c
Just like using an app icon to brand the updates for an app, this makes it a bit more obvious what the updates are.
(cherry picked from commit eae0bfdd79427727db5706797bda747d19b12c8a)
https://phabricator.endlessm.com/T34634
> eos-updater: Use the OS logo for minor update rows

- src/gs-app-context-bar.c
- src/gs-app-context-bar.ui
These tend to be either alarming or confusing for Endless OS users.
https://phabricator.endlessm.com/T35252
> gs-app-context-bar: Hide the Safety and Hardware tiles

- lib/gs-metered.c
In `block_scheduler_schedule_cb`, a `GCancellable::cancelled` signal handler was connected to a tasks's cancellable, with a pointer to the task itself as data. However, this was done without incrementing the reference count for the task, resulting in an error due to the task being prematurely freed when `g_cancellable_disconnect` was called.
In addition to handling that case, we will change `block_check_cb` to increment the task's reference count while it is in use.
https://phabricator.endlessm.com/T35306
> flatpak: Count all references to task in block_scheduler_schedule_cb
