endlessm/gnome-software

src/plugins/Makefile.am
src/plugins/gs-plugin-eos.c

This plugin so now handles the addition and removal of shortcuts from
the EOS desktop.

Add EOS desktop plugin

---

debian/changelog
debian/control

Replaces xdg-app by flatpak and updates the changelog.

Debian master flatpak

---

src/gs-application.c

https://phabricator.endlessm.com/T12035

Prefer the dark theme

---

src/gs-shell-overview.c
src/gs-shell-overview.ui

https://phabricator.endlessm.com/T12193

Use a GtkFlowBox for displaying the popular apps in the overview

---

src/plugins/gs-plugin-eos.c

https://phabricator.endlessm.com/T11382

plugin/eos: Add app to desktop after it is installed

---

src/plugins/gs-plugin-eos.c

https://phabricator.endlessm.com/T12325

eos: Blacklist the system's GNOME Software

---

src/gtk-style.css

https://phabricator.endlessm.com/T12288

Show the 'installed' tag when hovering the image tiles

---

src/plugins/gs-plugin-eos.c

https://phabricator.endlessm.com/T12326

eos: Implement the launch of core apps

---

src/org.gnome.Software.desktop.in

https://phabricator.endlessm.com/T10840
https://phabricator.endlessm.com/T12405

Remove DBusActivatable

---

configure.ac
data/icons/Makefile.am
data/icons/categories/Makefile.am
src/gs-plugin-loader.c
src/plugins/gs-desktop-common.c

https://phabricator.endlessm.com/T12235

Merge "Development" category into "Utilities"

---

src/gs-image-tile.c

https://phabricator.endlessm.com/T12501

Set the app thumbnail to the right widget in GsImageTile

---

src/gs-shell.c

The unmapped signal handler removes dialogs from the ptr array
keeping track of dialogs. However, this signal handler might get
run when we set the ptr array's size to zero, which causes memmove
to be run twice.
Block the unmapped signal handler when resizing the array so that
this doesn't happen.
http://phabricator.endlessm.com/T12461

gs-shell: Block the unmapped signal handler when destroying dialogs

---

src/plugins/gs-plugin-external-apps.c

external-apps: Support decompressing data.tar.xz for deb assets

---

src/plugins/gs-plugin-external-apps.c

in this PR we first reorganize the external-apps plugin a bit so that we can easily add more fields to the json, then implement a tar extractor (with a tar json type).
that's all folks.
https://phabricator.endlessm.com/T12251

T12251 -- Add suport for Dropbox

---

debian/control

https://phabricator.endlessm.com/T12561

Bump appstream-glib needed version to 0.6.1

---

debian/rules

https://phabricator.endlessm.com/T12639

T12639 debian

---

src/plugins/gs-plugin-eos.c

https://phabricator.endlessm.com/T12712

eos: Blacklist OpenArena in the es_GT image

---

src/gs-shell-details.c

https://phabricator.endlessm.com/T12566

Fix showing the progress bar when installing apps

---

src/gs-shell-updates.c

https://phabricator.endlessm.com/T12841

Don't show the details from the updates page if the app is a runtime

---

src/plugins/gs-appstream.c

The cache was not taking into account the branch, so when a runtime
with the same name was available with different branches it would
cache and use the first one found, thus not assigning the runtime
versions to apps.
https://phabricator.endlessm.com/T12844

Fix caching runtimes in gs-appstream

---

src/gs-shell-details.c

https://phabricator.endlessm.com/T12879

Do not show Updated: Never in the apps' details page

---

debian/gnome-software.install

Install PolicyKit rules and policy

---

debian/gnome-software.install

https://phabricator.endlessm.com/T13001

Add runtimes removal script

---

src/plugins/Makefile.am

https://phabricator.endlessm.com/T13011

eos: Fix building the plugin with the needed sources

---

Makefile.am
configure.ac
data/Makefile.am
data/eos-external-apps-enable.service.in
data/eos-external-apps.conf
data/g-s-helper.conf
src/plugins/Makefile.am
src/plugins/eos-external-apps-build-install
src/plugins/eos-external-apps-enable

Needed for ostree upgrades.
https://phabricator.endlessm.com/T12949

Setup external apps repo at runtime

---

src/plugins/gs-flatpak.c

This is a work-around for a problem related to uninstalling an app from
the installed view and having the other app views (e.g. in the category
views) not aware of the new state. This means that uninstalling an app
from the installed view and selecting it from its category view would
still show the app as installed.
This patch forces a refine when: the app is refined in the details
view and the app is installed but no Flatpak installed ref is found.
https://phabricator.endlessm.com/T13024

gs-flatpak: Force refining the state under certain circumstances

---

debian/changelog
debian/control
debian/rules

https://phabricator.endlessm.com/T13147

Debian T13147

---

src/gs-plugin-loader.c

We still want those apps to be discoverable by the user.
https://phabricator.endlessm.com/T12725

Do not filter out compulsory apps from the category views

---

debian/gnome-software.install

https://phabricator.endlessm.com/T12454

Install gnome-software-install-appstream

---

src/gtk-style.css

It looks out of place.
https://phabricator.endlessm.com/T13167

gtk-style: remove shadows when hovering overview tiles

---

debian/gnome-software.install

https://phabricator.endlessm.com/T12454

Install org.gnome.software.external-appstream.policy file

---

src/plugins/gs-plugin-external-apps.c

https://phabricator.endlessm.com/T13920

external-apps: Initialize a GError to prevent a possible segfault

---

src/plugins/gs-plugin-eos.c

This happened because two different objects sometimes represent the
same app.
https://phabricator.endlessm.com/T14101

eos: Fix apps mistakenly blacklisting themselves

---

data/org.gnome.software.gschema.xml
src/gs-screenshot-image.c
src/gs-utils.c

https://phabricator.endlessm.com/T13859

Fix stale screenshots when they are cached

---

src/plugins/gs-plugin-external-apps.c

These changes add support for launching Flatpak apps from outside
Flatpak, meaning that we can use Flatpak for the distribution/management
of the apps but we launch them from outside (without a sandbox).
This is a work-around for getting Google Chrome (at least for now)
because inside the Flatpak sandbox there is no setuid (which Chrome
needs to set up its own sandbox). Turning Chrome's sandbox off would
allow it to be launched from inside Flatpak but with a warning stating
warning the user about eventual security issues.
For accomplishing this, we use a new AppStream special metadata key
called 'flatpak-3rdparty::system-desktop-file'.
https://phabricator.endlessm.com/T14103

external-apps: Support launching apps with system desktop files

---

src/plugins/gs-flatpak.c

If the authentication fails when the user is removing a Flatpak, we need
to return a plugin "authentication failed" error as any other error will
be ignored by the plugin loader.
https://phabricator.endlessm.com/T14240

Return auth error in the Flatpak plugins when auth fails on removal

---

src/plugins/gs-plugin-eos.c

This way we can have many apps that can be confusing for the user, such
as service apps, that are updated seamlessly and possibly together with
others.
Currently the applications used in the proxy are currently the
com.endlessm.Platform runtime and the com.endlessm.EknServices app.
https://phabricator.endlessm.com/T12538

eos: Use a proxy app for updating a couple of applications

---

debian/gnome-software.install

https://phabricator.endlessm.com/T13869

Remove inexistent paths from debian/gnome-software.install

---

src/gs-shell-overview.c
src/gs-shell-overview.ui

https://phabricator.endlessm.com/T14712

Hide the "Editor's Picks" label in the featured page

---

src/gtk-style.css

https://phabricator.endlessm.com/T14710

Fix wrong declaration of font sizes in the image-tile CSS

---

src/plugins/gs-flatpak.c

In Endless OS, we ship our own customized versions of some core apps
such as the file manager or different media players/viewers and thus
we don't want to show them as duplicates in GNOME Software due to
having the GNOME flatpak repository added, which contain some of them.
Note that this is not the right fix but a quick workaround that should
serve us for now, as it hardcodes the list of options and gives no
options to the user on whether to decide to hide or show those apps (a
GSetting key would be nice), but it's the best thing we can do for now,
so the plan is to land it and revisit the plan early next year.
Also, this patch modifies the gs-flatpak plugin directly, which is not
nice either because the black listing mechanism that is used in
gs-plugin-eos is not enough: if a flatpak …

Don't show duplicated entries for flatpaks from the GNOME repository

---

src/gs-image-tile.ui

https://phabricator.endlessm.com/T14867

Fix image tiles' name and summary alignment according to specs

---

src/plugins/gs-plugin-eos.c

Google Chrome needs to be launched from outside the Flatpak sandbox so
the EOS plugin now adds a special key to the Chrome app which indicates
that it uses a special desktop file in order to be launched.
It also overrides the launch method in the EOS plugin to be able to
launch Chrome.
https://phabricator.endlessm.com/T14847

eos: Fix launching Google Chrome

---

src/gs-application.c
src/gs-plugin-loader.c
src/gs-plugin-loader.h

Based on a patch from Mario Sanchez Prada <mario@endlessm.com>, many thanks.
https://phabricator.endlessm.com/T15017

Use the same app instance when using --install= and the regular plugin methods

---

src/plugins/gs-flatpak.c

In eos 3.1 we introduced flatpak 0.6.13 and the possibility of
fetching the default branch for a given flatpak remote out of
the OSTree server's summary file, removing the need to have
a GNOME Software-specific configuration file for that. Also,
new 3.1 images will have that value set already in the local
configuration files, as that's how the image is built.
However, on 3.0.x systems upgrading to 3.1 it could happen
that they boot on 3.1 with no internet connection, in which
case GNOME Software has no way to know what the default branch
for eos-apps is (it would have been fetched from the server
otherwise), meaning it would show many versions of the same app.
To fix this, add a fallback mechanism so that if the default
branch is not set at and can't be retrieved at the time GNOME …

Add fallback for the eos-apps repository's default-branch

---

src/gs-shell-details.c
src/gs-shell-details.ui

https://phabricator.endlessm.com/T14949

Emphasize the add/remove shortcut buttons in the details page

---

src/plugins/gs-desktop-common.c

This category had been merged into utilities but now needs to be more
emphasized.
https://phabricator.endlessm.com/T14863

Add the development category

---

src/plugins/gs-plugin-eos.c

When the desktop app info couldn't be retrieved there was a crash
because of searching the hashtable of shrotcuts with a NULL string.
https://phabricator.endlessm.com/T15336

eos: Prevent crash when adding an app shortcut

---

src/plugins/gs-plugin-eos.c

The GDesktopFileInfo is only found when the app is installed, so when
we need to remove the shortcut from the EOS plugin after the app is
uninstalled, the GDesktopFileInfo is never found and the desktop is not
successfully removed.
To fix that these changes use the apps' ID directly from the GsApp
objects instead. The reason why it hasn't been used like that from the
beginning is that initially we'd have more info that just the app ID
(like a prefix describing which format the app had).
https://phabricator.endlessm.com/T16112

eos: Do not rely on GDesktopFileInfo for shortcuts

---

src/plugins/gs-flatpak.c

This is an ugly hack to try to overcome network issues that sometimes
lead to hitting errors when installing/updating apps that would lead
to having the process failing, when just retrying would likely work.
It is of course not a real fix and it's probably only useful with the
G_TLS_ERROR_NO_TLS that sometimes glib-networking spits out for no
reason, but we want to try it to see if at least reduces failures.
https://phabricator.endlessm.com/T16317

Retry installing/updating a flatpak after 3 seconds on error

---

src/plugins/gs-flatpak.c

When installing an application, if it is already installed then we
should recover from the error instead of aborting the operation.
https://phabricator.endlessm.com/T16370

Prevent errors when the apps are already installed

---

src/plugins/gs-plugin-eos.c

Or we will fail to correctly update the state when installing or
removing an app.
https://phabricator.endlessm.com/T16469

eos: consider kde4 prefix also when checking desktop shortcuts

---

src/plugins/gs-flatpak.c

When a file is missing from a commit, updates to the respective app
will fail if using static deltas.
This patch looks for such errors and retries the update without static
deltas.
https://phabricator.endlessm.com/T14158

Retry update without static deltas

---

src/plugins/gs-plugin-eos.c

https://phabricator.endlessm.com/T16926

eos: Fix leak when failing to get list of apps from the shell

---

debian/control
debian/rules

https://phabricator.endlessm.com/T15972

Bump appstream-glib's dependency to 0.6.7

---

plugins/flatpak/gs-flatpak.c

When an app's non-default branch is installed and the default one isn't,
then the latter will show up as installed because the apps are getting
mixed up.
This is due to merging apps that are created by parsing the installed
desktop files without setting their branch.
These changes set the branch for the mentioned apps which not only fixes
the state for the default branch app in the example mentioned above, but
also show the non-default branch app (as it should be because it is
installed).
https://phabricator.endlessm.com/T17055

Assign the branch to Flatpak apps coming from installed desktop files

---

src/gs-discovery-feed-content-provider.c

We only need three apps that we display in the feed. Rotate
the list of apps returned seeded by the current day of the
week.

DiscoveryFeed: limit installable apps returned and rotate list

---

src/gs-discovery-feed-content-provider.c

https://phabricator.endlessm.com/T17490

feed: Limit results to apps that have discovery feed content

---

src/gs-page.c

https://phabricator.endlessm.com/T18018

Do not abort if a page does not handle the reload vfunc

---

plugins/eos/gs-plugin-eos.c

When refining the apps, look for the metadata key
Endless::ReplacedByDesktopFile. This key indicates the desktop
file from another app that replaces this app on the desktop. We'll
use this functionality in order to replace the "Get X" placeholder
apps with their real application once the installation has
completed.
https://phabricator.endlessm.com/T18657

eos: Look up icon to replace and call ReplaceAppIfPossible

---

plugins/eos/gs-plugin-eos.c

Apps coming from the sdk.gnome.org or flathub.org remotes need to be
whitelisted on ARM, otherwise they are blocked.
The reason is that many apps did not work on ARM when we tested them.
https://phabricator.endlessm.com/T18914

eos: Use a whitelist for Flatpak apps when on ARM

---

plugins/eos/gs-plugin-eos.c

https://phabricator.endlessm.com/T18944

eos: blacklist evergreen apps

---

plugins/eos/gs-plugin-eos.c

The apps are the Quote of the Day and Word of the Day.
https://phabricator.endlessm.com/T18944

eos: Add Evergreen apps to the proxy app

---

src/gs-details-page.c

In a future rebase this commit should be squashed with
b5d50a57bf86d4608b26d82750f1f128fb842f0b.
https://phabricator.endlessm.com/T19696

Always highlight the "Add to desktop" button

---

plugins/eos/gs-plugin-eos.c

The EOS plugin needs to keep track of which apps started or stopped
having shortcuts in the desktop, in order to apply the right quirks to
the app objects.
However, the way this was being done was confusing (it was cleaning the
list of shortcuts on every refine) and had problems like: when the
desktop shortcut was added, removed, and re-added again, then the
correct quirk were not set because the list of apps with shortcuts
was not being correctly updated (i.e. the correct shortcut button would
not be shown).
These changes refactor the way the shortcuts are handled. Now EOS keeps
the list of shortcuts up to date, from the beginning, and every time
a shortcut is changed, which simplifies the code. The mentioned mistake
in updating the shortcut quirk is fixed as well. …

eos: Refactor how the shortcuts are handled

---

plugins/eos/gs-plugin-eos.c
plugins/flatpak/gs-flatpak.c

All of the possible versions of EknServices should be hidden by the
"Endless Platform" proxy app.
https://phabricator.endlessm.com/T19806

eos: Add com.endlessm.EknServices2 to proxy app

---

plugins/eos/gs-plugin-eos.c

https://phabricator.endlessm.com/T20328

T20328: apply whitelist to subdomains of flathub.org

---

plugins/eos/gs-plugin-eos.c

https://phabricator.endlessm.com/T20322

T20322: remove Steam from blacklisted Flathub apps

---

debian/gnome-software.install

https://phabricator.endlessm.com/T16949

Install the mime type related files

---

plugins/eos/gs-plugin-eos.c

We have experienced a few times already that sometimes apps are
mistakenly blacklisted, and it is sometimes very difficult to reproduce
the conditions in which that happens. Thus, in order to have better
hints in the future about possibly mistaken blacklisting of apps, this
patch adds debug messages to all the places that blacklist apps in the
EOS plugin.
https://phabricator.endlessm.com/T20108

eos: Always report why an app's been blacklisted

---

src/gs-discovery-feed-content-provider.c

We have to build up an array of unique indices and then pick those
ones out of the list.
https://phabricator.endlessm.com/T21028

feed: Select up to MAX_INSTALLABLE_APPS at random

---

plugins/eos/gs-plugin-eos.c

https://phabricator.endlessm.com/T21060

eos: Include com.endlessm.CompanionAppService as part of Endless Platform

---

src/gs-background-tile.ui

https://phabricator.endlessm.com/T22499

Add tooltips to the background tile's status icons

---

src/gs-update-monitor.c

https://phabricator.endlessm.com/T22492

Only show an app tile as having a scheduled update if there's one

---

plugins/flatpak/gs-flatpak.c

When installing/updating an app, if its related refs and its runtime
need to be installed as well, then they do. However, refs that are
related to the runtime itself do not get installed, and this is a
problem because some apps may need them (besides being a discrepancy
between using the Flatpak CLI and GNOME Software for installing Flatpak
apps).
Thus, these changes add any refs related to an app's runtime to the
list of refs that should be installed when installing or updating an
app. Note that it deliberately doesn't update refs related to the
runtime though, just as it doesn't update the runtime when updating an
app. Thus, refs that are related to the runtime get updated together
with it.
https://phabricator.endlessm.com/T22716

flatpak: Include related refs to the app's runtime on install/update

---

src/gs-shell.c

Fallout from commit 54863ceaf54cf5128f19b7f6e4338905a1b155d0
https://phabricator.endlessm.com/T23365

Restore window activation while showing a local file

---

lib/gs-plugin-job-private.h
lib/gs-plugin-job.c
lib/gs-plugin-job.h
lib/gs-plugin-loader.c
lib/gs-plugin-loader.h
lib/gs-plugin-types.h
lib/gs-plugin-vfuncs.h
lib/gs-plugin.c
meson.build
plugins/flatpak/gs-flatpak.c
plugins/flatpak/gs-flatpak.h
plugins/flatpak/gs-plugin-flatpak.c
src/gs-details-page.c
src/gs-details-page.ui
src/gs-page.c
src/gs-page.h

This implements copying Flatpaks to USB through a new button on the details page.

T20146 copy usb apps

---

src/gs-shell.c

https://phabricator.endlessm.com/T21533

fixup! shell: only show "Examine Disk" button when baobab is available

---

lib/gs-ioprio.c
lib/gs-ioprio.h
lib/gs-plugin-loader.c
lib/meson.build
meson.build

https://phabricator.endlessm.com/T23724

T23724: handle long-running (install, update, etc) ops at idle IO scheduler class

---

data/org.gnome.Software.mime.xml
po/es.po
po/gnome-software.pot
po/id.po
po/pt_BR.po

Add main languages' translation updates for G-S and nautilus (pt, id and es).

transifex: Add USB Translations

---

data/org.gnome.Software.mime.xml
po/es.po
po/gnome-software.pot
po/id.po
po/pt_BR.po

Add OS USB translations for (pt_BR,id,es) and correct one typo on the
mime xml file for the indonesian language.
https://phabricator.endlessm.com/T23777

transifex: Add OS USB updates translations

---

plugins/eos/gs-plugin-eos.c

The list of featured and blacklisted violent apps includes a few which were
migrated.
https://phabricator.endlessm.com/T23856

Update hardcoded app IDs to match rename

---

plugins/eos/gs-plugin-eos.c

This reverts commit 6ca717dd9bc767ea40a3162cec3313a0dd734ab4.
https://phabricator.endlessm.com/T24006

Revert "eos: Block coding chatbox if the coding feature is disabled"

---

plugins/flatpak/gs-flatpak.c

https://phabricator.endlessm.com/T23938

flatpak: Port to flatpak_installation_get_min_free_space_bytes

---

lib/gs-app.h
plugins/eos/gs-plugin-eos.c
src/gs-details-page.c

https://phabricator.endlessm.com/T24017

T24017 Apply parental controls to Launch button

---

lib/gs-plugin-loader.c

https://phabricator.endlessm.com/T23928
(cherry-picked from 62f6314f9f1262ac7b3c5d78bb96fe57240f7d4f)

trivial: Never show cancelled error messages to the user

---

plugins/eos/gs-plugin-eos.c

We're migrating Skype to the Flathub version.
https://phabricator.endlessm.com/T24741

eos: remove Skype from duplicate apps blacklist

---

plugins/eos/gs-plugin-eos.c

https://phabricator.endlessm.com/T25498

Hack: add LightSpeed to list of proxied app for the HackComponents

---

src/gs-details-page.c
src/gs-details-page.ui

Untested, reckless, drive-by patch spotted while working on OpenQA things.

Improve capitalisation and mnemonics of USB buttons

---

plugins/flatpak/gs-flatpak.c

https://phabricator.endlessm.com/T25495
https://phabricator.endlessm.com/T26042

T25495 fix pending updates

---

lib/gs-category.c
lib/gs-category.h
src/gs-shell.c

https://phabricator.endlessm.com/T26187

T26187 Fix crash when a USB drive is inserted

---

plugins/eos/gs-plugin-eos.c

https://phabricator.endlessm.com/T27150

eos: Ban violent/adult apps from solutions/spark products

---

plugins/core/gs-appstream.c
plugins/eos/gs-plugin-eos.c
plugins/flatpak/gs-plugin-flatpak.c
src/gs-loading-page.c

Various commits to reinstate features from
https://phabricator.endlessm.com/T27182
This is part of the [gnome-software 3.32 rebase](https://phabricator.endlessm.com/T25367).

T27182 flatpak dropped changes

---

plugins/flatpak/gs-flatpak.c
plugins/shell-extensions/gs-plugin-shell-extensions.c

Backport of https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/290. The shell-extensions commit had a minor cherry-pick conflict.

Minor leak fixes

---

src/gs-details-page.c
src/gs-details-page.ui

https://phabricator.endlessm.com/T27332

gs-details-page: Multiple UI fixes

---

plugins/eos-blacklist/gs-plugin-eos-blacklist.c
plugins/eos-updater/gs-plugin-eos-updater.c
plugins/flatpak/gs-flatpak.c
plugins/flatpak/gs-plugin-flatpak.c
src/gs-background-tile.c
src/gs-details-page.c
src/gs-overview-page.c

https://phabricator.endlessm.com/T25941

T25941 Fix offline USB app updates

---

plugins/core/gs-plugin-appstream.c

parsing appdata files
Problem statement:
This has been a recurring problem since a long time now, where
apps have started to drop the ".desktop" suffix from their `<id>`
tag present in their appdata. Reasoning for this change is given
as the ".desktop" is not really a part of the app-id. Also,
it's been seen as better aligning with flatpak ref-ids as
dropping this suffix makes the app-id equivalent to the flatpak
ref-id.
However, this breaks the mapping between the app's appdata and
it's desktop file. GNOME Software parses both of these, to merge
the metadata (ideally) under one GsApp object during refines.
The appdata supplies information like description and categories
whereas desktop files supplies information like icon, NoDisplay
and so on.
So, things will break if metadata parsing of …

appstream: Override <id> with <launchable type="desktop-id"> while

---

po/ar.po
po/fr.po
po/hi.po
po/zh_TW.po

I have removed
the newlines
that were in
the strings
And which
you were probably
rejecting
at build time
Forgive me
they were extraneous
so sour
and so wrong
https://phabricator.endlessm.com/T27764

Updates from Transifex

---

plugins/eos-blacklist/gs-plugin-eos-blacklist.c
plugins/flatpak/gs-flatpak.c

https://phabricator.endlessm.com/T28503

Improve caching/performance

---

plugins/flatpak/gs-flatpak.c
src/gs-background-tile.c
src/gs-common.c
src/gs-common.h
src/gs-details-page.c
src/gs-feature-tile.c
src/gs-popular-tile.c
src/gs-side-filter-row.c
src/gs-summary-tile.c
src/gs-upgrade-banner.c

Trivial backport of https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/357.
No associated Phabricator task.

Backport leak fixes from upstream

---

src/gs-content-rating.c
src/gs-content-rating.h
src/gs-details-page.c

Trivial backport of https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/356.
No associated task.

Backport ratings UI fixes from upstream

---

src/gs-details-page.c
src/gs-details-page.ui

https://phabricator.endlessm.com/T28699

Improve UX for removing apps

---

lib/gs-plugin-loader.c
lib/gs-plugin-loader.h
src/gs-details-page.c

https://phabricator.endlessm.com/T26219

Set spinner only on app copying to usb

---

debian/changelog

https://phabricator.endlessm.com/T28771
---
**Do not merge this through the GitHub UI!**
Code changes: https://github.com/endlessm/gnome-software/pull/530

debian: Update changelog from Salsa for 3.36.0 release

---

lib/gs-plugin-loader.c
plugins/core/gs-plugin-desktop-menu-path.c
plugins/core/gs-plugin-hardcoded-blacklist.c
plugins/core/gs-plugin-icons.c
plugins/core/gs-plugin-key-colors-metadata.c
plugins/core/gs-plugin-key-colors.c
plugins/core/gs-plugin-provenance-license.c
plugins/core/gs-plugin-provenance.c
plugins/core/gs-plugin-rewrite-resource.c
plugins/eos-blacklist/gs-plugin-eos-blacklist.c
plugins/fedora-pkgdb-collections/gs-plugin-fedora-pkgdb-collections.c
plugins/flatpak/gs-flatpak.c
plugins/flatpak/gs-plugin-flatpak.c
plugins/malcontent/gs-plugin-malcontent.c
plugins/modalias/gs-plugin-modalias.c
plugins/odrs/gs-plugin-odrs.c
plugins/packagekit/gs-plugin-packagekit-refine.c
plugins/repos/gs-plugin-repos.c
plugins/snap/gs-plugin-snap.c
src/gs-category-page.c

Various performance improvements backported from:
* https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/439
* https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/440
* https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/441
* https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/442
and with some comparable EOS-only fixes at the beginning of the branch.
This is a partial effort to regain the performance lost with the fix for https://phabricator.endlessm.com/T29286.

T29286 Various performance improvements

---

lib/gs-app-list.c
lib/gs-app.c
lib/gs-app.h
lib/gs-plugin-loader.c
lib/gs-self-test.c
plugins/flatpak/gs-flatpak-transaction.c
plugins/flatpak/gs-flatpak.c
plugins/flatpak/gs-self-test.c
src/gs-details-page.c
src/gs-loading-page.c
src/gs-progress-button.c
src/gs-upgrade-banner.c

This is a trivial cherry-pick of the upstream commits from:
* https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/444 (trivial, included to avoid cherry-pick conflicts)
* https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/448 (the actual fixes)
None of the commits conflicted.
https://phabricator.endlessm.com/T29774

T29774 Improve flatpak progress reporting

---

plugins/flatpak/gs-flatpak-transaction.c

Use GHashTableIter rather than g_hash_table_get_keys()
It’s a lot faster, as it doesn’t have to iterate through the table to
get the keys (and allocate a linked list for them), then the caller
iterate through that and query the hash table for *each* of them, and
then iterate through the list again to free it.
Not that this is a performance bottleneck, but the use of
`g_hash_table_get_{keys,values}()` irks me.
This introduces no functional changes.

fixup! transaction: Sync main app's state if a related ref is installed

---

lib/gs-debug.c
lib/gs-metered.c
lib/gs-metered.h
plugins/flatpak/gs-plugin-flatpak.c
plugins/fwupd/gs-plugin-fwupd.c
plugins/packagekit/gs-plugin-packagekit-refresh.c
src/gs-shell.c
src/gs-updates-page.c

https://phabricator.endlessm.com/T30209

T30209 Remove scheduled entries

---

debian/changelog
debian/rules

https://phabricator.endlessm.com/T21809

debian: Enable unit tests

---

src/org.gnome.Software.desktop.in

This is a follow-up to the rebase in https://phabricator.endlessm.com/T30171.
https://phabricator.endlessm.com/T30293

T30293 Drop speedwagon support

---

debian/changelog
debian/gnome-software.install

https://phabricator.endlessm.com/T30294

debian: Drop Discovery Feed support

---

plugins/eos/gs-plugin-eos.c
src/gs-details-page.ui
src/gtk-style.css

Follow-up from https://phabricator.endlessm.com/T30171.
https://phabricator.endlessm.com/T30446

T30446 Drop desktop shortcuts support

---

plugins/flatpak/gs-flatpak.c

Per the documentation for flatpak_installation_list_remotes_by_type(),
USB type remotes are not returned by that function by Flatpak 1.7.1 or
later. So use a different strategy to add apps to the USB category when
a drive is inserted.
flatpak_installation_list_remote_refs_sync() also does not work any more
for sideload repo URLs, so this commit makes changes to avoid using that
as well. That is solvable though; we could change Flatpak upstream to
fix that.
https://phabricator.endlessm.com/T30368

flatpak: Fix adding apps to USB category

---

src/gs-upgrade-banner.ui

Fixes #1619
Upstream: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1178
https://phabricator.endlessm.com/T33015

upgrade-banner: Allow wrapping title

---

plugins/eos-blocklist/gs-plugin-eos-blocklist.c

This tackles the small and easy part of https://phabricator.endlessm.com/T33045

T33045 Drop some unnecessary app filtering

---

plugins/eos-blocklist/gs-plugin-eos-blocklist.c

This implements all the proposals from https://phabricator.endlessm.com/T33045#928839 except number 4 (`gs_plugin_eos_blocklist_kapp_if_needed()`) as it’s a bit more in-depth.
https://phabricator.endlessm.com/T33045

T33045 Drop more filtering from eos-blocklist plugin
